/* DHCP console browser workflow; use a fresh profile.
 * &shot=noserver|addscope|wizard|exclusions|wizdns|leases|reservation|options|scope|ipv4props|filters|stopped|stats|unauth stops there for a screenshot. */
(async function () {
  'use strict';
  const WS = window.WS, M = WS.dhcp, D = WS.dhcpmgmt;
  let pass = 0, fail = 0;
  const t = (name, ok, detail) => { ok ? pass++ : fail++; console.log(`${ok ? 'PASS' : 'FAIL'} ${name}${!ok && detail !== undefined ? ' :: ' + JSON.stringify(detail) : ''}`); };
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const shade = () => [...document.querySelectorAll('#dialogs .dlg-shade')].pop();
  const dlgText = () => (shade() ? shade().textContent : '');
  const button = (label, scope = shade()) => [...scope.querySelectorAll('button')].find(x => x.textContent.trim() === label);
  const click = async (label, scope) => { const b = button(label, scope); if (!b) throw new Error('Missing button: ' + label); b.click(); await wait(70); };
  const input = (key, scope = shade()) => scope.querySelector(`[data-field="${key}"]`);
  const fill = (key, value, scope) => {
    const el = input(key, scope); if (!el) throw new Error('Missing field: ' + key);
    if (el.type === 'checkbox' || el.type === 'radio') el.checked = value; else if (el.tagName === 'SELECT' && typeof value === 'number') el.selectedIndex = value; else el.value = value;
    el.dispatchEvent(new Event(['checkbox', 'radio'].includes(el.type) || el.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true }));
  };
  const press = async (key, scope) => { const b = input(key, scope); if (!b) throw new Error('Missing button: ' + key); b.click(); await wait(70); };
  const tab = async label => { const b = [...shade().querySelectorAll('.ps-tab')].find(x => x.textContent === label); if (!b) throw new Error('Missing tab: ' + label); b.click(); await wait(30); };
  const stop = name => { if (new URLSearchParams(location.search).get('shot') !== name) return false; console.log(`RESULT ${pass} passed, ${fail} failed`); return true; };
  const item = (items, name) => { const it = items.find(x => x && x.label && WS.ui.plain(x.label) === name); if (!it) throw new Error('Missing menu item: ' + name + ' in ' + items.filter(x => x && x.label).map(x => WS.ui.plain(x.label)).join('|')); return it; };
  const has = (items, name) => items.some(x => x && x.label && WS.ui.plain(x.label) === name);
  const ps = new WS.ps.Session({ console: new WS.term.TextConsole() });
  const run = async cmd => { const out = []; await ps.execute(cmd, { capture: out }); return out; };
  const SID = '192.168.1.0';
  const client = () => WS.state.network.peers.find(p => p.name === 'CLIENT01');
  const releaseRouter = async () => { WS.state.network.lan.dhcp.enabled = false; M.refreshLeases(); await wait(120); };
  try {
    await wait(250);
    /* ---------------- no DHCP role ---------------- */
    const win = WS.apps.launch('dhcpmgmt'), c = win.dhcpmgmt, mmc = c.mmc;
    t('DHCP is a registered console titled DHCP', win.app === 'dhcpmgmt' && !!mmc && win.el.textContent.includes('DHCP'));
    t('without the role the DHCP root has no server', !mmc.tree.node('dhcp-srv'));
    t('result pane explains how to add a DHCP server', win.el.textContent.includes('Add a DHCP Server') && win.el.textContent.includes('click Add Server'));
    t('root menu offers Add Server...', has(mmc.scopeMenu(mmc.current()), 'Add Server...'));
    if (stop('noserver')) return;
    let adding = D.addServer({ console: c }); await wait(60); fill('name', WS.sys.name); await click('OK');
    t('adding this server without the role fails as RPC unavailable', dlgText().includes('RPC server is unavailable'));
    await click('OK'); await adding;

    /* ---------------- workgroup DHCP server ---------------- */
    WS.net.setStatic('Ethernet', { ip: '192.168.1.10', prefix: 24, gateway: '192.168.1.1' });
    WS.features.install(['DHCP'], { includeManagementTools: true }); await wait(150);
    const srv = () => mmc.tree.node('dhcp-srv');
    t('installed role shows the server by lower-case FQDN', srv() && srv().label === WS.sys.fqdn().toLowerCase());
    t('running workgroup server has the green check badge', srv().icon.includes('#0f7b0f'));
    c.open('dhcp-srv'); await wait(40);
    const srvMenu = mmc.scopeMenu(mmc.current());
    t('server menu follows the snap-in', ['Add/Remove Bindings...', 'Backup...', 'Restore...', 'Define User Classes...', 'Define Vendor Classes...', 'Reconcile All Scopes...', 'Set Predefined Options...', 'All Tasks', 'Delete', 'Refresh', 'Properties', 'Help'].every(n => has(srvMenu, n)));
    t('workgroup server cannot be authorized', !has(srvMenu, 'Authorize') && !has(srvMenu, 'Unauthorize'));
    const tasks = item(srvMenu, 'All Tasks').items();
    t('All Tasks: Start disabled, Stop/Restart enabled while running', item(tasks, 'Start').disabled && !item(tasks, 'Stop').disabled && !item(tasks, 'Restart').disabled);
    t('server pane lists IPv4 and IPv6', mmc.list && mmc.list.rows().map(r => r.label).join() === 'IPv4,IPv6');
    c.open('dhcp-v4'); await wait(40);
    t('IPv4 with no scopes shows Add a Scope', win.el.textContent.includes('Add a Scope') && win.el.textContent.includes('click New Scope'));
    const v4Menu = mmc.scopeMenu(mmc.current());
    t('IPv4 menu follows the snap-in', ['Display Statistics...', 'New Scope...', 'New Superscope...', 'New Multicast Scope...', 'Configure Failover...', 'Define User Classes...', 'Define Vendor Classes...', 'Reconcile All Scopes...', 'Set Predefined Options...', 'Properties'].every(n => has(v4Menu, n)));
    if (stop('addscope')) return;

    /* ---------------- New Scope Wizard ---------------- */
    let wz, wd;
    let wizard = D.newScope({ onCreate: (w, data) => { wz = w; wd = data; } }); await wait(60);
    t('wizard opens on the Wizard 97 welcome page', wz.page.id === 'welcome' && wz.el.textContent.includes('Welcome to the New Scope Wizard'));
    await click('Next >', wz.el);
    t('Next stays disabled until a scope name is typed', wz.page.id === 'name' && button('Next >', wz.el).disabled);
    fill('name', 'Lab LAN', wz.el); fill('description', 'Lab clients', wz.el);
    t('typing a name enables Next', !button('Next >', wz.el).disabled);
    await click('Next >', wz.el);
    fill('start', '192.168.1.100', wz.el);
    t('start address fills length and mask from the LAN', input('length', wz.el).value === '24' && input('mask', wz.el).value === '255.255.255.0');
    fill('length', '16', wz.el);
    t('length and subnet mask stay in sync', input('mask', wz.el).value === '255.255.0.0');
    fill('mask', '255.255.255.0', wz.el);
    fill('end', '192.168.2.10', wz.el);
    if (stop('wizard')) return;
    await click('Next >', wz.el);
    t('range in two subnets is rejected and keeps the page', dlgText().includes('not in the same subnet') && wz.page.id === 'range');
    await click('OK');
    fill('end', '192.168.1.200', wz.el); await click('Next >', wz.el);
    t('valid range moves to Add Exclusions and Delay', wz.page.id === 'exclusions');
    fill('exStart', '192.168.1.100', wz.el); fill('exEnd', '192.168.1.109', wz.el); await press('exAdd', wz.el);
    fill('exStart', '192.168.1.150', wz.el); await press('exAdd', wz.el);
    const exList = () => [...input('exList', wz.el).options].map(o => o.textContent);
    t('exclusions list ranges and single addresses', exList().join('|') === '192.168.1.100 to 192.168.1.109|Address 192.168.1.150', exList());
    fill('exStart', '192.168.1.50', wz.el); await press('exAdd', wz.el);
    t('exclusion outside the range is rejected', dlgText().includes('not within the scope address range'));
    await click('OK');
    fill('exList', 1, wz.el); await press('exRemove', wz.el);
    t('Remove takes the exclusion off the list', exList().length === 1);
    if (stop('exclusions')) return;
    await click('Next >', wz.el);
    t('lease duration defaults to 8 days', wz.page.id === 'lease' && input('days', wz.el).value === '8' && input('hours', wz.el).value === '0');
    await click('Next >', wz.el);
    t('options page defaults to configure now', wz.page.id === 'options' && input('configure-yes', wz.el).checked);
    await click('Next >', wz.el);
    t('router page Add is disabled while the address is empty', wz.page.id === 'router' && input('routerAdd', wz.el).disabled);
    fill('routerIp', '192.168.1.1', wz.el); await press('routerAdd', wz.el);
    t('router address added to the list', wd.routers.join() === '192.168.1.1');
    await click('Next >', wz.el);
    t('DNS page: workgroup server has no parent domain or local DNS', wz.page.id === 'dns' && input('domain', wz.el).value === '' && wd.dns.length === 0);
    fill('dnsServer', 'router', wz.el); await press('dnsResolve', wz.el);
    t('Resolve fills the IP address through name resolution', input('dnsIp', wz.el).value === '192.168.1.1');
    await press('dnsAdd', wz.el);
    t('a responding DNS server is added without a prompt', wd.dns.join() === '192.168.1.1' && !shade().textContent.includes('valid DNS server'));
    fill('dnsIp', '192.168.1.77', wz.el); input('dnsAdd', wz.el).click(); await wait(80);
    t('a non-DNS address asks before adding', dlgText().includes('does not belong to a valid DNS server'));
    await click('No');
    t('answering No leaves the list unchanged', wd.dns.join() === '192.168.1.1');
    fill('domain', 'lab.local', wz.el);
    if (stop('wizdns')) return;
    await click('Next >', wz.el);
    t('WINS page may be left empty', wz.page.id === 'wins');
    await click('Next >', wz.el);
    t('activate page defaults to activate now', wz.page.id === 'activate' && input('activate-yes', wz.el).checked);
    await click('Next >', wz.el);
    t('wizard completes on the Completing page', wz.page.id === 'complete' && wz.el.textContent.includes('Completing the New Scope Wizard'));
    await click('Finish', wz.el); const done = await wizard;
    const sc = M.scope(SID);
    t('Finish creates the scope through the model', done.finished && sc && sc.name === 'Lab LAN' && sc.start === '192.168.1.100' && sc.end === '192.168.1.200' && sc.prefix === 24 && sc.leaseDays === 8, sc);
    t('scope is active with its exclusion', sc.active && sc.exclusions.length === 1 && sc.exclusions[0].end === '192.168.1.109');
    t('scope options 003, 006 and 015 are set', JSON.stringify(sc.options) === JSON.stringify({ 3: ['192.168.1.1'], 6: ['192.168.1.1'], 15: 'lab.local' }), sc.options);
    await wait(80); mmc.tree.expand('dhcp-v4');
    t('new scope appears in the open console tree', mmc.tree.node('dhcp-scope:' + SID) && mmc.tree.node('dhcp-scope:' + SID).label === 'Scope [192.168.1.0] Lab LAN');
    const scopeRow = mmc.list && mmc.list.rows().find(r => r.scopeId === SID);
    t('IPv4 pane lists the scope as ** Active ** with folders', scopeRow && scopeRow.status === '** Active **' && ['Server Options', 'Policies', 'Filters'].every(n => mmc.list.rows().some(r => r.label === n)));
    let out = await run('Get-DhcpServerv4Scope');
    t('PowerShell sees the console scope', out.length === 1 && out[0].ScopeId === SID && out[0].Name === 'Lab LAN' && out[0].State === 'Active' && out[0].LeaseDuration === '8.00:00:00', out.map(x => x.Name));
    out = await run(`Get-DhcpServerv4ExclusionRange -ScopeId ${SID}`);
    t('PowerShell sees the wizard exclusion', out.length === 1 && out[0].StartRange === '192.168.1.100');

    /* ---------------- leases ---------------- */
    await releaseRouter();
    t('CLIENT01 leases the first free address from the scope', client().leasedFrom === 'server' && client().ip === '192.168.1.110', client());
    c.open('dhcp-leases:' + SID); await wait(50);
    let lease = mmc.list.rows().find(r => r.ip === '192.168.1.110');
    t('Address Leases shows the client with its unique ID', lease && lease.uid === '00155d010132' && lease.type === 'DHCP' && /CLIENT01/.test(lease.name), lease);
    t('Address Leases has the snap-in columns', ['Client IP Address', 'Name', 'Lease Expiration', 'Type', 'Unique ID', 'Description', 'Network Access Protection', 'Probation Expiration', 'Filter'].every(n => mmc.list.columns().some(x => x.label === n)));

    /* ---------------- reservation ---------------- */
    let frame;
    let res = D.newReservation(SID, { onCreate: f => { frame = f; } }); await wait(50);
    t('New Reservation prefills the network prefix', input('ip').value === '192.168.1.');
    fill('name', 'CLIENT01'); fill('ip', '192.168.1.60'); fill('mac', '00-15-5D-01-01-32'); fill('description', 'Front desk');
    if (stop('reservation')) return;
    await click('Add');
    t('Add creates the reservation and keeps the dialog open', M.scope(SID).reservations.some(r => r.ip === '192.168.1.60' && r.mac === '00-15-5D-01-01-32') && frame.shade.isConnected && input('name').value === '');
    fill('name', 'Other'); fill('ip', '192.168.1.60'); fill('mac', '00155d0000aa'); await click('Add');
    t('duplicate reservation address shows the model error', dlgText().includes('currently taken by another client'));
    await click('OK'); await click('Close'); await res;
    M.refreshLeases(); await wait(100);
    t('CLIENT01 now gets its reserved address', client().ip === '192.168.1.60');
    lease = mmc.list.rows().find(r => r.ip === '192.168.1.60');
    t('reserved client shows Reservation (active)', lease && lease.expires === 'Reservation (active)' && lease.description === 'Front desk', lease);
    c.open('dhcp-res:' + SID); await wait(40); mmc.tree.expand('dhcp-res:' + SID);
    t('reservation node appears under Reservations', mmc.tree.node(`dhcp-resv:${SID}:192.168.1.60`) && mmc.tree.node(`dhcp-resv:${SID}:192.168.1.60`).label === '[192.168.1.60] CLIENT01');
    t('Reservations pane lists the reservation', mmc.list.rows().map(r => r.label).join() === '[192.168.1.60] CLIENT01');
    out = await run(`Get-DhcpServerv4Reservation -ScopeId ${SID}`);
    t('PowerShell sees the reservation as Both', out.length === 1 && out[0].ClientId === '00-15-5d-01-01-32' && out[0].Type === 'Both');
    c.open('dhcp-leases:' + SID); await wait(40);
    if (stop('leases')) return;
    let sheet;
    D.reservationProperties(SID, '192.168.1.60', { onCreate: s => { sheet = s; } }); await wait(50);
    fill('description', 'Reception PC'); fill('typeDhcp', true); await click('OK');
    t('reservation properties apply through the model', M.scope(SID).reservations[0].description === 'Reception PC' && M.scope(SID).reservations[0].type === 'Dhcp');
    await run('Set-DhcpServerv4Reservation -IPAddress 192.168.1.60 -Description "Lobby PC" -Type Both');
    t('Set-DhcpServerv4Reservation edits the same reservation', M.scope(SID).reservations[0].description === 'Lobby PC' && M.scope(SID).reservations[0].type === 'Both');

    /* ---------------- exclusions ---------------- */
    let ex = D.newExclusion(SID, { onCreate: f => { frame = f; } }); await wait(50);
    fill('start', '192.168.1.190'); fill('end', '192.168.1.199'); await click('Add');
    t('Add Exclusion Range adds and stays open', M.scope(SID).exclusions.some(e => e.start === '192.168.1.190' && e.end === '192.168.1.199') && frame.shade.isConnected && input('start').value === '');
    fill('start', '192.168.1.195'); await click('Add');
    t('overlapping exclusion is rejected', dlgText().includes('overlaps an existing exclusion range'));
    await click('OK'); await click('Close'); await ex;
    c.open('dhcp-pool:' + SID); await wait(50);
    t('Address Pool lists the range and both exclusions', mmc.list.rows().length === 3 && mmc.list.rows()[0].description === 'Address range for distribution' && mmc.list.rows()[2].description === 'IP Addresses excluded from distribution');
    out = await run(`Get-DhcpServerv4ExclusionRange -ScopeId ${SID}`);
    t('PowerShell sees both exclusions', out.length === 2);
    mmc.list.select(['ex:192.168.1.190']);
    let busy = item(mmc.contextFor('result'), 'Delete').action(); await wait(60);
    t('deleting an exclusion asks first', dlgText().includes('delete the selected exclusion range'));
    await click('Yes'); await busy; await wait(60);
    t('confirmed delete removes the exclusion', M.scope(SID).exclusions.length === 1 && mmc.list.rows().length === 2);

    /* ---------------- options ---------------- */
    D.configureOptions(SID, { onCreate: s => { sheet = s; } }); await wait(60);
    t('Scope Options lists the predefined options with checkboxes', shade().textContent.includes('003 Router') && input('opt-3').checked && !input('opt-42').checked);
    fill('opt-42', true); fill('optIp', '192.168.1.1'); await press('optAdd');
    sheet.select(15); await wait(20); fill('optValue', 'contoso.lab');
    fill('opt-46', true); fill('optValue', '0x8');
    fill('opt-44', true);
    if (stop('options')) return;
    await click('OK');
    t('checked IP option without addresses is refused', dlgText().includes('requires at least one IP address'));
    await click('OK'); fill('opt-44', false); await click('OK');
    let o = M.scope(SID).options;
    t('options dialog writes ip, string and byte options', JSON.stringify(o[42]) === '["192.168.1.1"]' && o[15] === 'contoso.lab' && o[46] === 8 && !(44 in o), o);
    D.configureOptions(null, { onCreate: s => { sheet = s; } }); await wait(60);
    t('server level dialog is titled Server Options', shade().textContent.includes('Server Options'));
    fill('opt-4', true); fill('optIp', '192.168.1.10'); await press('optAdd'); await click('OK');
    t('server option saved', JSON.stringify(M.serverOptions()[4]) === '["192.168.1.10"]');
    c.open('dhcp-sopt:' + SID); await wait(60);
    const optRows = mmc.list.rows();
    const router = optRows.find(r => r.code === 3), inherited = optRows.find(r => r.code === 4);
    t('Scope Options pane shows name, vendor, value and policy', router && router.name === '003 Router' && router.vendor === 'Standard' && router.value === '192.168.1.1' && router.policy === 'None');
    t('inherited server option is shown with the server option icon', inherited && inherited.level === 'inherited' && mmc.view().icon(inherited) === D.ICON.serverOption && mmc.view().icon(router) === D.ICON.option);
    t('byte option shows as hex', optRows.find(r => r.code === 46).value === '0x8');
    mmc.list.select(['42']);
    busy = item(mmc.contextFor('result'), 'Delete').action(); await wait(60); await click('Yes'); await busy;
    t('deleting a scope option removes it', !(42 in M.scope(SID).options));
    out = await run(`Get-DhcpServerv4OptionValue -ScopeId ${SID}`);
    t('PowerShell reads the console options', out.some(x => x.OptionId === 46 && x.Type === 'Byte') && out.some(x => x.OptionId === 15 && String(x.Value) === 'contoso.lab'));

    /* ---------------- scope properties ---------------- */
    D.scopeProperties(SID, { onCreate: s => { sheet = s; } }); await wait(60);
    t('scope properties title and read-only mask', shade().textContent.includes('Scope [192.168.1.0] Lab LAN Properties') && shade().querySelector('input[readonly]').value === '255.255.255.0');
    fill('start', '10.0.0.5'); await click('Apply');
    t('start address outside the subnet is refused', dlgText().includes('overlaps with an existing range or is invalid'));
    await click('OK'); fill('start', '192.168.1.100'); fill('end', '192.168.1.220'); fill('days', '3'); fill('hours', '12');
    if (stop('scope')) return;
    await click('Apply');
    t('General tab applies range and lease through the model', M.scope(SID).end === '192.168.1.220' && Math.abs(M.scope(SID).leaseDays - 3.5) < 1e-9);
    await tab('Advanced'); fill('typeBoth', true); fill('delay', '10'); await click('OK');
    t('Advanced tab sets type and delay', M.scope(SID).type === 'Both' && M.scope(SID).delay === 10);
    out = await run(`Get-DhcpServerv4Scope ${SID}`);
    t('PowerShell shows the new lease duration and type', out[0].LeaseDuration === '3.12:00:00' && out[0].Type === 'Both' && out[0].EndRange === '192.168.1.220', out[0] && out[0].LeaseDuration);
    D.scopeProperties(SID); await wait(60); fill('unlimited', true);
    t('Unlimited disables the lease spinners', input('days').disabled && input('minutes').disabled);
    await click('OK'); out = await run(`Get-DhcpServerv4Scope ${SID}`);
    t('Unlimited lease reaches the model and PowerShell', M.scope(SID).leaseUnlimited && out[0].LeaseDuration === '10675199.02:48:05.4775807');
    D.scopeProperties(SID); await wait(60); fill('limited', true);
    t('Limited re-enables the spinners with the saved duration', !input('days').disabled && input('days').value === '3' && input('hours').value === '12');
    await click('OK');
    t('limited lease restored', !M.scope(SID).leaseUnlimited && Math.abs(M.scope(SID).leaseDays - 3.5) < 1e-9);

    /* ---------------- activate / deactivate / delete ---------------- */
    c.open('dhcp-scope:' + SID); await wait(40);
    t('scope menu follows the snap-in', ['Display Statistics...', 'Configure Failover...', 'Reconcile...', 'Deactivate', 'Delete', 'Properties'].every(n => has(mmc.scopeMenu(mmc.current()), n)));
    busy = item(mmc.scopeMenu(mmc.current()), 'Deactivate').action(); await wait(60);
    t('Deactivate asks for confirmation', dlgText().includes('Do you want to deactivate'));
    await click('No'); await busy;
    t('answering No keeps the scope active', M.scope(SID).active);
    busy = D.setActive(SID, false); await wait(60); await click('Yes'); await busy; await wait(120);
    t('deactivated scope gets the red down-arrow icon', !M.scope(SID).active && mmc.tree.node('dhcp-scope:' + SID).icon === D.ICON.scopeInactive);
    t('clients cannot lease from an inactive scope', /^169\.254\./.test(client().ip));
    item(mmc.scopeMenu(mmc.current()), 'Activate').action(); await wait(150);
    t('Activate needs no prompt and clients lease again', M.scope(SID).active && client().ip === '192.168.1.60');
    await run('Add-DhcpServerv4Scope -Name Temp -StartRange 10.0.0.10 -EndRange 10.0.0.50 -SubnetMask 255.255.255.0'); await wait(80);
    t('PowerShell scope shows up in the console', !!mmc.tree.node('dhcp-scope:10.0.0.0'));
    busy = D.deleteScope('10.0.0.0'); await wait(60);
    t('deleting an active scope warns first', dlgText().includes('currently active') && dlgText().includes('Do you want to delete Scope [10.0.0.0] Temp?'));
    await click('No'); await busy;
    t('No keeps the scope', !!M.scope('10.0.0.0'));
    busy = D.deleteScope('10.0.0.0'); await wait(60); await click('Yes'); await busy; await wait(80);
    out = await run('Get-DhcpServerv4Scope');
    t('confirmed delete removes it for PowerShell and the tree', out.length === 1 && !mmc.tree.node('dhcp-scope:10.0.0.0'));

    /* ---------------- filters ---------------- */
    c.open('dhcp-deny'); await wait(40);
    t('Allow and Deny start disabled', mmc.tree.node('dhcp-allow').icon === D.ICON.filterOff && mmc.tree.node('dhcp-deny').icon === D.ICON.filterOff);
    let nf = D.newFilter('deny', { onCreate: f => { frame = f; } }); await wait(50);
    fill('mac', '00155d010132'); fill('description', 'CLIENT01'); await click('Add');
    fill('mac', 'zz-12'); await click('Add');
    t('invalid MAC address is refused', dlgText().includes('MAC address is not valid'));
    await click('OK'); await click('Close'); await nf; await wait(60);
    t('New Filter stores a normalised MAC in the Deny list', M.filters().deny.length === 1 && M.filters().deny[0].mac === '00-15-5D-01-01-32');
    t('Deny pane lists the filter', mmc.list.rows().length === 1 && mmc.list.rows()[0].mac === '00-15-5d-01-01-32');
    out = await run('Get-DhcpServerv4Filter -List Deny');
    t('PowerShell sees the console filter', out.length === 1 && out[0].MacAddress === '00-15-5d-01-01-32' && out[0].List === 'Deny');
    M.refreshLeases(); await wait(60);
    t('a disabled Deny list does not block the client', client().ip === '192.168.1.60');
    D.ipv4Properties({ tab: 'Filters', onCreate: s => { sheet = s; } }); await wait(60);
    fill('denyEnabled', true);
    if (stop('ipv4props')) return;
    await click('OK'); await wait(150);
    t('IPv4 Properties enables the Deny list', M.filters().denyEnabled && mmc.tree.node('dhcp-deny').icon === D.ICON.deny);
    t('denied client gets no lease and falls back to APIPA', /^169\.254\./.test(client().ip) && client().leasedFrom === null);
    out = await run('Get-DhcpServerv4FilterList');
    t('PowerShell reports the Deny list enabled', out[0].Deny === true && out[0].Allow === false);
    if (stop('filters')) return;
    item(mmc.scopeMenu(mmc.current()), 'Disable').action(); await wait(150);
    t('Disable on the Deny node lets the client lease again', !M.filters().denyEnabled && client().ip === '192.168.1.60');
    mmc.list.select(['00-15-5D-01-01-32']);
    busy = item(mmc.contextFor('result'), 'Delete').action(); await wait(60); await click('Yes'); await busy;
    await run('Set-DhcpServerv4FilterList -Allow $true'); await wait(150);
    t('an empty enabled Allow list blocks every client', M.filters().allowEnabled && /^169\.254\./.test(client().ip));
    await run('Add-DhcpServerv4Filter -List Allow -MacAddress 00-15-5D-* -Description "Hyper-V clients"'); await wait(150);
    t('a wildcard Allow filter lets the client lease', client().ip === '192.168.1.60' && mmc.tree.node('dhcp-allow').icon === D.ICON.allow);
    await run('Remove-DhcpServerv4Filter -MacAddress 00-15-5D-*'); await run('Set-DhcpServerv4FilterList -Allow $false'); await wait(150);
    t('filters removed and lists disabled from PowerShell', !M.filters().allow.length && !M.filters().allowEnabled && client().ip === '192.168.1.60');

    /* ---------------- leases: delete and add to reservation ---------------- */
    busy = D.deleteReservation(SID, '192.168.1.60'); await wait(60);
    t('deleting a reservation asks first', dlgText().includes('delete the reservation [192.168.1.60] CLIENT01'));
    await click('Yes'); await busy; await wait(150);
    t('client falls back to a dynamic lease', client().ip === '192.168.1.110' && !M.scope(SID).reservations.length);
    c.open('dhcp-leases:' + SID); await wait(50);
    mmc.list.select(['192.168.1.110']);
    item(mmc.contextFor('result'), 'Add to Reservation').action(); await wait(80);
    t('Add to Reservation reserves the leased address', M.scope(SID).reservations.some(r => r.ip === '192.168.1.110' && r.mac === '00-15-5D-01-01-32'));
    M.removeReservation(SID, '192.168.1.110');
    mmc.list.select(['192.168.1.110']);
    busy = item(mmc.contextFor('result'), 'Delete').action(); await wait(60); await click('Yes'); await busy;
    t('Delete removes the lease from the server', !M.leases(SID).some(l => l.ip === '192.168.1.110'));
    M.refreshLeases(); await wait(80);
    t('the client renews and its lease reappears', M.leases(SID).some(l => l.ip === '192.168.1.110'));
    await run('Remove-DhcpServerv4Lease -IPAddress 192.168.1.110');
    t('Remove-DhcpServerv4Lease deletes it through the same model', ps.lastSuccess && !M.leases(SID).some(l => l.ip === '192.168.1.110'));
    M.refreshLeases(); await wait(80);

    /* ---------------- service stop / start ---------------- */
    c.open('dhcp-srv'); await wait(40);
    item(item(mmc.scopeMenu(mmc.current()), 'All Tasks').items(), 'Stop').action(); await wait(200);
    t('Stop shows the Service Control progress', dlgText().includes('Windows is attempting to stop the following service') && dlgText().includes('DHCP Server'));
    await wait(1200);
    t('stopped service gives the server the red stopped badge', !WS.svc.isRunning('DHCPServer') && srv().icon.includes('M10.7 10.7'));
    t('stopped server hides IPv4/IPv6 and explains', !mmc.tree.node('dhcp-v4') && win.el.textContent.includes('Cannot find the DHCP Server'));
    await run('Get-DhcpServerv4Scope');
    t('PowerShell also fails while the service is stopped', !ps.lastSuccess);
    if (stop('stopped')) return;
    item(item(mmc.scopeMenu(mmc.current()), 'All Tasks').items(), 'Start').action(); await wait(1400);
    t('Start brings the service and IPv4 back', WS.svc.isRunning('DHCPServer') && !!mmc.tree.node('dhcp-v4') && srv().icon.includes('#0f7b0f'));

    /* ---------------- statistics / reconcile ---------------- */
    D.statistics(null, { onCreate: f => { frame = f; } }); await wait(60);
    const stat = n => (frame.list.rows().find(r => r.label === n) || {}).value;
    const st = M.statistics();
    t('Display Statistics shows the real counters', ['Start Time', 'Up Time', 'Discovers', 'Offers', 'Delayed Offers', 'Requests', 'Acks', 'Nacks', 'Declines', 'Releases', 'Total Scopes', 'Scopes with delay configured', 'Total Addresses', 'In Use', 'Available'].every(n => stat(n) !== undefined));
    t('statistics are computed from the model', stat('Total Scopes') === '1' && stat('Total Addresses') === String(st.totalAddresses) && st.totalAddresses === 111 && stat('In Use').startsWith(st.inUse + ' (') && stat('Scopes with delay configured') === '1', [stat('Total Addresses'), stat('In Use')]);
    t('Up Time uses Days/Hours/Minutes/Seconds', /^\d+ Days, \d+ Hours, \d+ Minutes, \d+ Seconds$/.test(stat('Up Time')));
    if (stop('stats')) return;
    await click('Close');
    out = await run(`Get-DhcpServerv4ScopeStatistics -ScopeId ${SID}`);
    t('PowerShell scope statistics agree with the console', out[0].Free === st.available && out[0].InUse === st.inUse);
    out = await run('Get-DhcpServerv4Statistics');
    t('Get-DhcpServerv4Statistics reports the server counters', out[0].TotalScopes === 1 && out[0].TotalAddresses === st.totalAddresses && out[0].AddressesInUse === st.inUse);
    D.statistics(SID, { onCreate: f => { frame = f; } }); await wait(60);
    t('scope statistics show the address counts only', dlgText().includes('Scope 192.168.1.0 Statistics') && frame.list.rows().length === 3);
    await click('Close');
    busy = D.reconcile(SID); await wait(60); await click('Verify'); await wait(60);
    t('Reconcile verifies the database', dlgText().includes('The database is consistent.'));
    await click('OK'); await busy;

    /* ---------------- domain controller: authorization ---------------- */
    WS.state.system.adminPassword = 'ForestP@ss2025!';
    WS.features.install(['AD-Domain-Services'], { includeManagementTools: true });
    WS.sys.onBoot();
    const promoted = WS.ad.installForest({ domainName: 'contoso.local', safeModePassword: 'RestoreP@ss2025!', noReboot: true });
    WS.sys.onBoot(); await wait(250);
    t('domain fixture promotes through the shared model', promoted.ok, promoted);
    t('server node now shows the domain FQDN', srv().label === WS.sys.fqdn().toLowerCase() && srv().label.endsWith('.contoso.local'));
    t('unauthorized DC server has the red down-arrow badge', srv().icon.includes('M12 10.3v3.2') && mmc.tree.node('dhcp-v4').icon.includes('M12 10.3v3.2'));
    c.open('dhcp-srv'); await wait(50);
    t('unauthorized server explains authorization', win.el.textContent.includes('Authorize the DHCP Server') && win.el.textContent.includes('press F5'));
    t('unauthorized DC server cannot lease', /^169\.254\./.test(client().ip));
    t('boot logged event 1046 for the unauthorized server', WS.evt.list('System').some(e => e.id === 1046));
    if (stop('unauth')) return;
    item(mmc.scopeMenu(mmc.current()), 'Authorize').action(); await wait(150);
    t('Authorize authorizes in AD and the badge turns green', M.authorized && srv().icon.includes('#0f7b0f') && client().ip === '192.168.1.110');
    out = await run('Get-DhcpServerInDC');
    t('PowerShell lists the authorized server', out.length === 1 && out[0].DnsName === WS.sys.fqdn().toLowerCase());
    busy = item(mmc.scopeMenu(mmc.current()), 'Unauthorize').action(); await wait(60);
    t('Unauthorize asks first', dlgText().includes('Are you sure you want to unauthorize'));
    await click('No'); await busy;
    t('No keeps the server authorized', M.authorized);
    busy = D.unauthorize(); await wait(60); await click('Yes'); await busy; await wait(80);
    t('Yes unauthorizes the server', !M.authorized && has(mmc.scopeMenu(mmc.current()), 'Authorize'));
    await run('Add-DhcpServerInDC'); await wait(100);
    t('Add-DhcpServerInDC updates the open console', M.authorized && srv().icon.includes('#0f7b0f'));
    wizard = D.newScope({ onCreate: (w, data) => { wz = w; wd = data; } }); await wait(60);
    await click('Next >', wz.el); fill('name', 'Second', wz.el); await click('Next >', wz.el);
    fill('start', '10.10.0.10', wz.el);
    t('class A start address defaults to length 8', input('length', wz.el).value === '8');
    fill('length', '24', wz.el); fill('end', '10.10.0.50', wz.el); await click('Next >', wz.el); await click('Next >', wz.el);
    fill('days', '0', wz.el); await click('Next >', wz.el);
    t('zero lease duration is refused', dlgText().includes('at least one minute'));
    await click('OK'); fill('days', '1', wz.el); await click('Next >', wz.el);
    fill('configure-no', true, wz.el); await click('Next >', wz.el);
    t('configure later skips straight to Completing', wz.page.id === 'complete');
    await click('< Back', wz.el); fill('configure-yes', true, wz.el); await click('Next >', wz.el); await click('Next >', wz.el);
    t('DC: DNS page prefills the domain and this DNS server', input('domain', wz.el).value === 'contoso.local' && wd.dns.join() === '192.168.1.10');
    await click('< Back', wz.el); await click('< Back', wz.el); fill('configure-no', true, wz.el); await click('Next >', wz.el); await click('Finish', wz.el); await wizard;
    t('scope configured later is created inactive without options', M.scope('10.10.0.0') && !M.scope('10.10.0.0').active && !Object.keys(M.scope('10.10.0.0').options).length && M.scope('10.10.0.0').leaseDays === 1);

    /* ---------------- console housekeeping ---------------- */
    busy = c.removeServer(); await wait(60); await click('Yes'); await busy; await wait(60);
    t('Delete removes the server from this console only', !srv() && WS.svc.isRunning('DHCPServer'));
    adding = D.addServer({ console: c }); await wait(60); fill('name', WS.sys.name); await click('OK'); await adding; await wait(60);
    t('Add Server puts this server back', !!srv());
    const sm = WS.sm.open('dashboard');
    [...sm.el.querySelectorAll('.sm-menu')].find(x => x.textContent === 'Tools').click(); await wait(30);
    t('Server Manager Tools lists DHCP', document.querySelector('#dialogs').textContent.includes('DHCP'));
    WS.ui.closeMenu(); sm.close(); win.restore();
    c.open('dhcp-leases:' + SID); await wait(60);
  } catch (e) {
    fail++; console.log('FAIL exception ' + e.message + ' ' + (e.stack || '').split('\n').slice(0, 5).join(' | '));
  }
  console.log(`RESULT ${pass} passed, ${fail} failed`);
})();
