/* File Explorer browser workflow; use a fresh profile. &shot=pc|folder|props stops there for a screenshot. */
(async function () {
  'use strict';
  const WS = window.WS;
  let pass = 0, fail = 0;
  const t = (name, ok, detail) => { ok ? pass++ : fail++; console.log(`${ok ? 'PASS' : 'FAIL'} ${name}${!ok && detail !== undefined ? ' :: ' + JSON.stringify(detail) : ''}`); };
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const shade = () => [...document.querySelectorAll('#dialogs .dlg-shade')].pop();
  const dlgText = () => (shade() ? shade().textContent : '');
  const click = async label => { const b = [...shade().querySelectorAll('button')].find(x => x.textContent.trim() === label); if (!b) throw new Error('Missing button: ' + label); b.click(); await wait(70); };
  const stop = name => { if (new URLSearchParams(location.search).get('shot') !== name) return false; console.log(`RESULT ${pass} passed, ${fail} failed`); return true; };
  try {
    await wait(250);
    /* ---------------- desktop icons (real hit-testing, so a layer on top of them fails) ---------------- */
    const icon = name => [...document.querySelectorAll('#desktop-icons .desk-icon')].find(i => i.textContent === name);
    const hit = el => { const r = el.getBoundingClientRect(); return document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2); };
    const fire = (el, type, o = {}) => { const r = el.getBoundingClientRect(); el.dispatchEvent(new MouseEvent(type, { bubbles: true, cancelable: true, clientX: r.left + r.width / 2, clientY: r.top + r.height / 2, ...o })); };
    t('the desktop shows Recycle Bin and Lab Guide', !!icon('Recycle Bin') && !!icon('Lab Guide'));
    const target = hit(icon('Lab Guide'));
    t('a click on a desktop icon reaches the icon, not the window layer', !!target && !!target.closest('.desk-icon'), target && (target.id || target.className));
    fire(target, 'click');
    t('clicking selects it', icon('Lab Guide').classList.contains('sel'));
    const blank = document.elementFromPoint(40, 600);
    fire(blank, 'pointerdown'); fire(blank, 'click');
    t('clicking empty desktop clears the selection', blank && blank.closest('#desktop') && !icon('Lab Guide').classList.contains('sel'), blank && (blank.id || blank.className));
    fire(hit(icon('Lab Guide')), 'dblclick'); await wait(80);
    t('double-clicking Lab Guide opens it', !!WS.wm.find('lab'));
    WS.wm.find('lab').close();
    fire(hit(icon('Lab Guide')), 'click');
    document.activeElement.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); await wait(80);
    t('Enter opens the selected icon', !!WS.wm.find('lab'));
    WS.wm.find('lab').close();
    fire(hit(icon('Recycle Bin')), 'contextmenu'); await wait(40);
    let menu = [...document.querySelectorAll('.menu.ctx')].pop();
    t('right-clicking an icon gives its own menu (Open first, bold)', !!menu && menu.querySelector('.menu-item.default') && menu.querySelector('.menu-item.default').textContent.includes('Open') && menu.textContent.includes('Empty Recycle Bin') && !menu.textContent.includes('Personalize'));
    menu.querySelector('.menu-item.default').click(); await wait(80);
    const rb = WS.wm.windows.find(w => w.app === 'explorer');
    t('Open on Recycle Bin opens it in File Explorer', !!rb && rb.explorer.path() === 'Recycle Bin');
    rb.close(); await wait(30);
    const win = WS.apps.launch('explorer'), x = win.explorer; await wait(60);
    t('opens on This PC with the drives', x.path() === 'This PC' && win.el.textContent.includes('Devices and drives') && x.items().includes('Local Disk (C:)') && x.items().includes('DVD Drive (D:)'));
    t('drive tile shows free space', /free of/.test(win.el.querySelector('.ex-drive').textContent));
    if (stop('pc')) return;
    const addr = win.el.querySelector('[data-field="address"]');
    addr.value = 'c:\\windows\\system32\\drivers\\etc'; addr.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); await wait(60);
    t('typing a path in the address bar opens it', x.path() === 'C:\\Windows\\System32\\drivers\\etc' && x.items().includes('hosts') && win.el.querySelector('.wm-title, .win-title') !== undefined);
    x.up(); await wait(30);
    t('Up goes to the parent folder', x.path() === 'C:\\Windows\\System32\\drivers');
    x.back(); await wait(30);
    t('Back returns', x.path() === 'C:\\Windows\\System32\\drivers\\etc');
    let busy = (async () => { x.go('C:\\NoSuchFolder'); })(); await wait(60);
    t('a missing path gets the Windows message', dlgText().includes("Windows can't find 'C:\\NoSuchFolder'."));
    await click('OK'); await busy;
    x.go('C:\\'); await wait(40);
    t('C:\\ lists folders first, without hidden items', x.items()[0] === 'PerfLogs' || x.items().indexOf('Windows') < x.items().findIndex(n => /\./.test(n)) || !x.items().some(n => /\./.test(n)));
    t('hidden folders are not listed', !x.items().includes('$RECYCLE.BIN') && !x.items().includes('System Volume Information'));
    const nf = x.newFolder(); await wait(40);
    t('New folder creates "New folder"', nf === 'New folder' && WS.fs.isDir('C:\\New folder'));
    t('a second one is "New folder (2)"', x.newFolder() === 'New folder (2)');
    busy = x.rename('New folder', 'Shares\\Bad'); await wait(60);
    t('invalid characters are refused', dlgText().includes("A file name can't contain any of the following characters"));
    await click('OK'); await busy;
    await x.rename('New folder', 'Projects'); await wait(30);
    t('rename goes through WS.fs', WS.fs.isDir('C:\\Projects') && !WS.fs.exists('C:\\New folder'));
    x.go('C:\\Projects'); await wait(30);
    const tf = x.newTextFile(); await wait(30);
    t('New Text Document creates an empty .txt', tf === 'New Text Document.txt' && WS.fs.readFile('C:\\Projects\\New Text Document.txt') === '');
    if (stop('folder')) return;
    /* inline rename, Notepad */
    const box = x.startRename(tf); await wait(40);
    t('rename edits the name in place, selecting the name without the extension', !!box && box.selectionEnd === 'New Text Document'.length);
    box.value = 'notes.txt'; box.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); await wait(60);
    t('Enter commits the rename', WS.fs.exists('C:\\Projects\\notes.txt') && x.items().includes('notes.txt'));
    x.go('C:\\Projects\\notes.txt'); await wait(60);
    const np = WS.wm.find('notepad');
    t('opening a text file starts Notepad on it', !!np && np.notepad.path() === 'C:\\Projects\\notes.txt' && np.el.textContent.includes('notes.txt - Notepad'));
    np.notepad.setText('Server build notes'); await wait(20);
    t('typing marks the title with *', np.el.querySelector('.np-text') && /^\*notes\.txt - Notepad/.test(document.title) || np.el.textContent.includes('*notes.txt - Notepad'));
    np.notepad.save(); await wait(30);
    t('Save writes through WS.fs (CRLF)', WS.fs.readFile('C:\\Projects\\notes.txt') === 'Server build notes' && !np.notepad.dirty());
    np.notepad.setText('changed'); busy = np.notepad.exit(); await wait(60);
    t('Exit with changes asks to save', dlgText().includes('Do you want to save changes to C:\\Projects\\notes.txt?'));
    await click("Don't Save"); await busy; await wait(30);
    t("Don't Save closes without saving", !WS.wm.find('notepad') && WS.fs.readFile('C:\\Projects\\notes.txt') === 'Server build notes');

    /* copy / cut / paste / drag and drop */
    x.go('C:\\Projects'); await wait(30);
    x.copy(['notes.txt']); await x.paste(); await wait(30);
    t('pasting a copy into the same folder names it "- Copy"', WS.fs.exists('C:\\Projects\\notes - Copy.txt'));
    WS.fs.mkdir('C:\\Projects\\Archive');
    x.cut(['notes - Copy.txt']); await wait(20);
    t('cut items are dimmed', !!win.el.querySelector('.lv-row.ex-cut'));
    await x.paste('C:\\Projects\\Archive'); await wait(30);
    t('paste of a cut item moves it', WS.fs.exists('C:\\Projects\\Archive\\notes - Copy.txt') && !WS.fs.exists('C:\\Projects\\notes - Copy.txt') && !x.clip());
    WS.fs.writeFile('C:\\Projects\\Archive\\notes.txt', 'old');
    x.copy(['notes.txt']); busy = x.paste('C:\\Projects\\Archive'); await wait(60);
    t('a name clash asks Replace / Skip', dlgText().includes('The destination already has a file named "notes.txt".'));
    await click('Replace'); await busy;
    t('Replace overwrites it', WS.fs.readFile('C:\\Projects\\Archive\\notes.txt') === 'Server build notes');
    WS.fs.writeFile('C:\\Projects\\moveme.txt', 'm');
    await x.drop(['C:\\Projects\\moveme.txt'], 'C:\\Projects\\Archive'); await wait(30);
    t('dragging onto a folder on the same drive moves', WS.fs.exists('C:\\Projects\\Archive\\moveme.txt') && !WS.fs.exists('C:\\Projects\\moveme.txt'));
    x.go('C:\\Projects\\Archive'); await wait(40);
    t('the navigation tree follows the current folder', x.tree().selected() && x.tree().selected().id === 'C:\\Projects\\Archive');

    /* Recycle Bin */
    await x.remove(['moveme.txt']); await wait(40);
    t('Delete moves to the Recycle Bin without asking', !shade() && !WS.fs.exists('C:\\Projects\\Archive\\moveme.txt') && WS.fs.recycleBin().some(r => r.name === 'moveme.txt' && r.origin === 'C:\\Projects\\Archive'));
    x.go('Recycle Bin'); await wait(40);
    t('the Recycle Bin lists it with its original location', win.el.textContent.includes('Original Location') && x.items().length === 1 && win.el.textContent.includes('C:\\Projects\\Archive'));
    await x.restore(WS.fs.recycleBin().map(r => r.id)); await wait(30);
    t('Restore puts it back', WS.fs.exists('C:\\Projects\\Archive\\moveme.txt') && !WS.fs.recycleBin().length);
    x.go('C:\\Projects\\Archive'); await wait(30);
    busy = x.remove(['moveme.txt'], { permanent: true }); await wait(60);
    t('Shift+Delete asks before deleting permanently', dlgText().includes('Are you sure you want to permanently delete this file?'));
    await click('Yes'); await busy;
    t('permanently deleted (not in the bin)', !WS.fs.exists('C:\\Projects\\Archive\\moveme.txt') && !WS.fs.recycleBin().length);
    await x.remove(['notes.txt']); x.go('Recycle Bin'); await wait(30);
    busy = x.emptyBin(); await wait(60); await click('Yes'); await busy;
    t('Empty Recycle Bin', !WS.fs.recycleBin().length);
    x.go('C:\\'); await wait(30);
    busy = x.remove(['Windows']); await wait(60);
    t('protected system folders cannot be deleted', dlgText().includes('You need permission to perform this action.') && WS.fs.isDir('C:\\Windows'));
    await click('OK'); await busy;

    /* Properties and Sharing */
    busy = x.properties('Projects'); await wait(60);
    t('folder Properties: General and Sharing', dlgText().includes('File folder') && dlgText().includes('Contains:2 Files, 1 Folders') && [...shade().querySelectorAll('.ps-tab')].map(e => e.textContent).join() === 'General,Sharing');
    [...shade().querySelectorAll('.ps-tab')].find(e => e.textContent === 'Sharing').click(); await wait(40);
    t('Sharing tab says Not Shared', dlgText().includes('C:\\Projects') && dlgText().includes('Not Shared'));
    if (stop('props')) return;
    const adv = [...shade().querySelectorAll('button')].find(b => b.textContent === 'Advanced Sharing...');
    adv.click(); await wait(80);
    const cb = shade().querySelector('[data-field="share"]'); cb.checked = true; cb.dispatchEvent(new Event('change', { bubbles: true }));
    await click('OK'); await wait(80);
    t('Advanced Sharing from Explorer creates the share', !!WS.smb.get('Projects') && dlgText().includes('Shared') && dlgText().includes(`\\\\${WS.sys.name}\\Projects`));
    await click('Cancel'); await busy;
    x.go('This PC'); await wait(30);
    busy = x.properties ? (async () => { x.go('C:\\'); await wait(30); return x.properties(); })() : null; await wait(120);
    t('drive Properties are the Disk Management sheet', dlgText().includes('Local Disk') && dlgText().includes('Drive C:'));
    await click('Cancel'); await busy;
    x.go('D:\\'); await wait(60);
    t('the empty DVD drive is not ready', dlgText().includes('The device is not ready.'));
    await click('OK');
    t('ncpa link: Explorer is the registered app (not the placeholder)', WS.apps.get('explorer').launch === WS.explorer.launch);
  } catch (e) {
    fail++; console.log('FAIL exception ' + e.message + ' ' + (e.stack || '').split('\n').slice(0, 5).join(' | '));
  }
  console.log(`RESULT ${pass} passed, ${fail} failed`);
})();
