/* Server Manager > File and Storage Services browser workflow; use a fresh profile.
 * &shot=volumes|disks|pools|newvolume|nvdisk|nvsize|nvfs|nvconfirm|nvresults|extend|newshare|nslocation|nsname|nssettings|nsperms|nsadvsec|nsresults|shares|shareprops|empty
 * stops there for a screenshot. */
(async function () {
  'use strict';
  const WS = window.WS;
  let pass = 0, fail = 0;
  const t = (name, ok, detail) => { ok ? pass++ : fail++; console.log(`${ok ? 'PASS' : 'FAIL'} ${name}${!ok && detail !== undefined ? ' :: ' + JSON.stringify(detail) : ''}`); };
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const shade = () => [...document.querySelectorAll('#dialogs .dlg-shade')].pop();
  const dlgText = () => (shade() ? shade().textContent : '');
  const click = async label => { const b = [...shade().querySelectorAll('button')].find(x => x.textContent.trim() === label); if (!b) throw new Error('Missing button: ' + label + ' in ' + dlgText().slice(0, 120)); b.click(); await wait(70); };
  const stop = name => { if (new URLSearchParams(location.search).get('shot') !== name) return false; console.log(`RESULT ${pass} passed, ${fail} failed`); return true; };
  const item = (items, name) => { const it = items.find(x => x && x.label === name); if (!it) throw new Error('Missing menu item: ' + name + ' in ' + items.filter(x => x && x.label).map(x => x.label).join('|')); return it; };
  const ps = new WS.ps.Session({ console: new WS.term.TextConsole() });
  const run = async cmd => { const out = []; await ps.execute(cmd, { capture: out }); return out; };
  const check = c => WS.labs.evalCheck(c, WS.state);
  const R = WS.smfss.rows, M = WS.smfss.menus, S = WS.storage, GB = S.GB, MB = S.MB;
  const name = () => WS.sys.name;
  const wzButton = (w, label) => [...w.el.querySelectorAll('.wz-buttons button')].find(b => b.textContent.trim() === label);
  const pageText = w => w.page._el.textContent;
  const fieldIn = (root, f) => root.querySelector(`[data-field="${f}"]`);
  const type = (el, value) => { el.value = value; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); };
  const tick = (cb, on) => { const i = cb.input || cb; if (i.checked !== on) i.click(); };
  try {
    await wait(250);
    /* ---------------- navigation ---------------- */
    const win = WS.sm.open('dashboard'); await wait(60);
    const tileEl = [...win.el.querySelectorAll('.sm-tile')].find(x => x.querySelector('.t').textContent.startsWith('File and Storage Services'));
    t('the dashboard has a File and Storage Services tile', !!tileEl);
    tileEl.querySelector('.t').click(); await wait(60);
    const crumb = () => win.el.querySelector('.sm-crumb').textContent;
    const subs = () => [...win.el.querySelectorAll('.sm-subnav > div')];
    t('the tile opens File and Storage Services on Servers', win.sm.page === 'fss:servers' && crumb() === 'Server Manager ▸ File and Storage Services ▸ Servers');
    t('the nav shrinks to its icons and the sub-pages get their own column', win.el.querySelector('.sm-nav').classList.contains('narrow') && getComputedStyle(win.el.querySelector('.sm-subnav')).display !== 'none'
      && subs().map(x => x.textContent).join('|') === 'Servers|Volumes|Disks|Storage Pools|Shares|iSCSI|Work Folders');
    t('Disks and Storage Pools are indented under Volumes', subs()[2].classList.contains('sub') && subs()[3].classList.contains('sub') && !subs()[1].classList.contains('sub'));
    t('Servers shows the servers, events and the role services', ['SERVERS', 'EVENTS', 'SERVICES'].every(x => win.el.querySelector('.sm-content').textContent.includes(x)) && win.el.querySelector('.sm-content').textContent.includes('LanmanServer'));
    subs()[2].click(); await wait(50);
    t('the breadcrumb nests Disks under Volumes', crumb() === 'Server Manager ▸ File and Storage Services ▸ Volumes ▸ Disks');
    win.sm.go('local'); await wait(40);
    t('leaving the sub-pages restores the full nav', !win.el.querySelector('.sm-nav').classList.contains('narrow') && getComputedStyle(win.el.querySelector('.sm-subnav')).display === 'none');
    [...win.el.querySelectorAll('.sm-nav > div')].find(x => x.textContent.includes('File and Storage Services')).click(); await wait(50);
    t('the nav entry returns to the last sub-page', win.sm.page === 'fss:disks');

    /* ---------------- volumes ---------------- */
    win.sm.go('fss:volumes'); await wait(50);
    const tileText = title => { const el = win.el.querySelector(`.sm-content [data-tile="${title}"]`); return el ? el.textContent : ''; };
    const rowsIn = title => [...win.el.querySelectorAll(`.sm-content [data-tile="${title}"] .lv-row`)];
    const pick = (title, text) => { const r = rowsIn(title).find(x => x.textContent.includes(text)); if (!r) throw new Error(`No row "${text}" in ${title}`); r.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, button: 0 })); return r; };
    const vols = R.volumes();
    t('Volumes lists C: and the hidden EFI and Recovery volumes, not the MSR', vols.length === 3 && vols.filter(r => /^\\\\\?\\Volume\{/.test(r.volume)).length === 2 && vols.some(r => r.volume === 'C:'));
    t('sizes use three significant digits', tileText('VOLUMES').includes('126 GB') && tileText('VOLUMES').includes('742 MB') && WS.smfss.size(40 * GB) === '40.0 GB' && WS.smfss.size(8 * MB) === '8.00 MB');
    t('the list is grouped under the server', tileText('VOLUMES').includes(`${name()} (3)`) && tileText('VOLUMES').includes('All volumes | 3 total'));
    t('lettered volumes are listed first', rowsIn('VOLUMES')[0].textContent.startsWith('C:'));
    t('nothing is selected yet, so the lower tiles explain themselves', tileText('SHARES').includes('Select a volume to display its related shares.') && tileText('DISK').includes('Select a volume to display its disk.'));
    pick('VOLUMES', 'C:'); await wait(30);
    t('selecting C: shows its disk', tileText('DISK').includes('Disk 0') && tileText('DISK').includes('GPT') && tileText('DISK').includes('127 GB') && WS.smfss.selection.volumes === 'vol:0:3');
    t('C: has no related shares', tileText('SHARES').includes('No related shares exist.'));
    const cm = M.volume(vols.find(r => r.volume === 'C:'));
    t('C: cannot be formatted, deleted, re-lettered or extended', ['Format...', 'Delete Volume', 'Manage Drive Letter and Access Paths...', 'Extend Volume...'].every(l => item(cm, l).disabled) && !item(cm, 'New Share...').disabled && !item(cm, 'Properties').disabled);
    t('the volume menu has the real commands in order', cm.filter(x => x.label).map(x => x.label).join('|') === 'New Share...|New iSCSI Virtual Disk...|Scan File System for Errors|Repair File System Errors|Manage Drive Letter and Access Paths...|Format...|Extend Volume...|Delete Volume|Configure Data Deduplication...|Properties');
    WS.store.changed('storage'); await wait(60);
    t('the selection survives a repaint', WS.smfss.selection.volumes === 'vol:0:3' && rowsIn('VOLUMES').find(r => r.classList.contains('sel')).textContent.startsWith('C:') && tileText('DISK').includes('Disk 0'));
    if (stop('volumes')) return;
    let busy = WS.smfss.scanVolume('C'); await wait(300);
    t('Scan File System for Errors reports no problems', dlgText().includes('Windows has scanned the file system and found no problems.'));
    await click('OK'); await busy;

    /* ---------------- disks and storage pools ---------------- */
    win.sm.go('fss:disks'); await wait(50);
    const disk1 = () => R.disks().find(r => r.number === 1);
    t('Disks lists Disk 0 online and Disk 1 offline, uninitialized', tileText('DISKS').includes('All disks | 2 total') && disk1().status === 'Offline' && disk1().partition === 'Unknown' && R.disks()[0].partition === 'GPT' && tileText('DISKS').includes('Msft Virtual Disk'));
    let dm = M.disk(disk1());
    t('an offline disk offers Bring Online, not Initialize or Take Offline', !item(dm, 'Bring Online').disabled && item(dm, 'Initialize').disabled && item(dm, 'Take Offline').disabled && item(dm, 'Reset Disk').disabled);
    t('the system disk cannot be taken offline or reset', item(M.disk(R.disks()[0]), 'Take Offline').disabled && item(M.disk(R.disks()[0]), 'Reset Disk').disabled);
    pick('DISKS', 'Offline'); await wait(30);
    t('an offline disk has no volumes to show and sits in the primordial pool', tileText('VOLUMES').includes('The disk is offline.') && tileText('STORAGE POOL').includes('Primordial'));
    if (stop('disks')) return;
    win.sm.go('fss:pools'); await wait(50);
    t('Storage Pools lists the primordial pool', tileText('STORAGE POOLS').includes('Primordial') && tileText('STORAGE POOLS').includes('Available Disks'));
    pick('STORAGE POOLS', 'Primordial'); await wait(30);
    t('its physical disks are the poolable ones (Disk 1, not the system disk)', rowsIn('PHYSICAL DISKS').length === 1 && tileText('PHYSICAL DISKS').includes('LUN 1') && tileText('VIRTUAL DISKS').includes('No related virtual disks exist.'));
    if (stop('pools')) return;
    win.sm.go('fss:disks'); await wait(40);
    busy = WS.smfss.bringOnline(1); await wait(60);
    t('Bring Online warns about data loss first', dlgText().includes('might cause data loss') && dlgText().includes('Bring Disk Online'));
    await click('Yes'); await busy; await wait(40);
    t('the disk comes online through WS.storage', S.disk(1).online && disk1().status === 'Online' && tileText('DISKS').includes('Online'));
    dm = M.disk(disk1());
    t('an online blank disk offers Initialize and Take Offline', !item(dm, 'Initialize').disabled && !item(dm, 'Take Offline').disabled && item(dm, 'Bring Online').disabled);
    busy = WS.smfss.takeOffline(1); await wait(60);
    await click('No'); await busy;
    t('answering No leaves it online', S.disk(1).online);

    /* ---------------- New Volume Wizard ---------------- */
    let nv = null, nvd = null;
    WS.sm.newVolume({ disk: 1, onCreate: (w, d) => { nv = w; nvd = d; } }); await wait(80);
    t('New Volume Wizard opens as its own window', !!nv && !!WS.wm.find('newvolume') && nv.el.textContent.includes('Before you begin'));
    t('its steps are the real ones', [...nv.el.querySelectorAll('.wz-step')].map(x => x.textContent).join('|') === 'Before You Begin|Server and Disk|Size|Drive Letter or Folder|File System Settings|Confirmation|Results');
    if (stop('newvolume')) return;
    await nv.next(); await wait(40);
    t('Server and Disk lists the server and the disks, with Disk 1 selected', pageText(nv).includes(name()) && pageText(nv).includes('Disk 1') && nvd.disk === 1 && pageText(nv).includes('40.0 GB'));
    if (stop('nvdisk')) return;
    nv.next(); await wait(80);
    t('a blank disk is initialized as GPT first', dlgText().includes('The selected disk will be initialized as a GPT disk.'));
    await click('OK'); await wait(80);
    t('and that happens at once', S.disk(1).style === 'GPT' && nv.page.id === 'size');
    t('Size shows the available capacity and the minimum', pageText(nv).includes('Available Capacity:') && pageText(nv).includes('40.0 GB') && pageText(nv).includes('8.00 MB'));
    const sizeBox = () => fieldIn(nv.page._el, 'size');
    type(sizeBox(), 'lots'); nv.next(); await wait(80);
    t('a size that is not a number is refused', dlgText().includes('The volume size is not valid.'));
    await click('OK');
    type(sizeBox(), '50'); nv.next(); await wait(80);
    t('a size above the available capacity is refused', dlgText().includes("can't be larger than the available capacity"));
    await click('OK');
    type(sizeBox(), '20'); await nv.next(); await wait(40);
    t('20 GB is accepted', nvd.bytes === 20 * GB && nv.page.id === 'letter');
    if (stop('nvsize')) return;
    t('the first free letter is offered (E:, because the DVD drive has D:)', fieldIn(nv.page._el, 'letter').value === 'E' && ![...fieldIn(nv.page._el, 'letter').options].some(o => o.value === 'C' || o.value === 'D'));
    fieldIn(nv.page._el, 'assign-folder').click(); nv.next(); await wait(80);
    t('a folder needs a path (the mount test covers folders fully)', dlgText().includes('Type the path of an empty folder on an NTFS volume'));
    await click('OK');
    fieldIn(nv.page._el, 'assign-letter').click();
    type(fieldIn(nv.page._el, 'letter'), 'F'); await nv.next(); await wait(40);
    t('F: is chosen', nvd.letter === 'F' && nv.page.id === 'fs');
    type(fieldIn(nv.page._el, 'fs'), 'ReFS'); await wait(20);
    t('ReFS offers 4K and 64K clusters and no short names', [...fieldIn(nv.page._el, 'au').options].map(o => o.textContent).join('|') === 'Default|4096|64K' && fieldIn(nv.page._el, 'shortnames').disabled);
    type(fieldIn(nv.page._el, 'au'), '65536'); type(fieldIn(nv.page._el, 'label'), 'Projects');
    if (stop('nvfs')) return;
    await nv.next(); await wait(40);
    t('Confirmation summarizes the choices', nv.page.id === 'confirm' && ['Disk 1', 'Volume size:20.0 GB', 'F:\\', 'Volume label:Projects', 'File system:ReFS', 'Allocation unit size:64K', 'Short file name creation:Disabled'].every(x => pageText(nv).includes(x)), pageText(nv));
    t('Create is enabled only on Confirmation', !wzButton(nv, 'Create').disabled && wzButton(nv, 'Next >').disabled);
    if (stop('nvconfirm')) return;
    wzButton(nv, 'Create').click(); await wait(400);
    t('Results reports success for every task', nv.page.id === 'results' && pageText(nv).includes('You have successfully completed the New Volume Wizard.') && (pageText(nv).match(/Completed/g) || []).length === 5);
    const f = S.volume('F');
    t('the volume is made through WS.storage', !!f && f.fs === 'ReFS' && f.label === 'Projects' && f.au === 65536 && Math.abs(f.size - 20 * GB) < MB && f.disk === 1 && WS.fs.isDir('F:\\'));
    t('Get-Volume agrees and reports its path', (await run('Get-Volume -DriveLetter F'))[0].FileSystem === 'ReFS' && /^\\\\\?\\Volume\{[0-9a-f]{8}-/.test((await run('Get-Volume -DriveLetter F'))[0].Path));
    if (stop('nvresults')) return;
    wzButton(nv, 'Close').click(); await wait(40);
    t('Close closes the wizard', !WS.wm.find('newvolume'));

    /* ---------------- extend ---------------- */
    win.sm.go('fss:volumes'); await wait(50);
    t('Volumes now lists F: with its label', tileText('VOLUMES').includes('F:') && tileText('VOLUMES').includes('Projects') && tileText('VOLUMES').includes('All volumes | 4 total'));
    pick('VOLUMES', 'F:'); await wait(30);
    t('F: shows Disk 1 in the DISK tile', tileText('DISK').includes('Disk 1'));
    let fm = M.volume(R.volumes().find(r => r.volume === 'F:'));
    t('F: can be extended, formatted and deleted', ['Extend Volume...', 'Format...', 'Delete Volume', 'Manage Drive Letter and Access Paths...'].every(l => !item(fm, l).disabled));
    busy = item(fm, 'Properties').action(); await wait(80);
    t("Properties opens Server Manager's own volume Properties", dlgText().startsWith('F: Properties') && dlgText().includes('File system:ReFS') && dlgText().includes('Label:'), dlgText().slice(0, 200));
    await click('Cancel'); await busy;
    let ex = null;
    busy = WS.smfss.extendVolume('F', { onCreate: fr => { ex = fr; } }); await wait(60);
    t('Extend Volume shows the current and maximum size', dlgText().includes('Current size:20.0 GB') && dlgText().includes('Maximum size:') && fieldIn(ex.body, 'size').value === String(Math.floor((S.supportedSize('F').max / GB) * 100) / 100));
    if (stop('extend')) return;
    type(fieldIn(ex.body, 'size'), '10'); ex.ok(); await wait(80);
    t('shrinking through Extend is refused', dlgText().includes('must be larger than the current size'));
    await click('OK');
    type(fieldIn(ex.body, 'size'), '45'); ex.ok(); await wait(80);
    t('more than the maximum is refused', dlgText().includes("can't be larger than the maximum size"));
    await click('OK');
    type(fieldIn(ex.body, 'size'), '30'); ex.ok(); await wait(60); await busy;
    t('30 GB extends the volume', Math.abs(S.volume('F').size - 30 * GB) < MB && !shade());
    busy = WS.smfss.extendVolume('F', { onCreate: fr => { ex = fr; } }); await wait(60);
    ex.ok(); await wait(60); await busy;
    t('the offered size takes all the space after the volume', S.supportedSize('F').max === S.volume('F').size && S.freeRegions(1).length === 0);
    S.resize('F', 30 * GB); await wait(20);

    /* ---------------- New Share Wizard ---------------- */
    let ns = null, nsd = null;
    WS.sm.newShare({ volume: 'F', onCreate: (w, d) => { ns = w; nsd = d; } }); await wait(80);
    t('New Share Wizard opens on the profiles', !!WS.wm.find('newshare') && ['SMB Share - Quick', 'SMB Share - Advanced', 'SMB Share - Applications', 'NFS Share - Quick', 'NFS Share - Advanced'].every(x => pageText(ns).includes(x)) && pageText(ns).includes('fastest way to create an SMB file share'));
    t('its steps are the real ones', [...ns.el.querySelectorAll('.wz-step')].map(x => x.textContent).join('|') === 'Select Profile|Share Location|Share Name|Other Settings|Permissions|Confirmation|Results');
    if (stop('newshare')) return;
    ns.page._el.querySelector('[data-profile="smb-adv"]').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true })); await wait(20);
    t('choosing a profile shows its description', pageText(ns).includes('Enable quotas'));
    await ns.next(); await wait(40);
    t('the server shows why the Advanced profile cannot be used', pageText(ns).includes('File Server Resource Manager is not installed'));
    ns.next(); await wait(80);
    t('and Next explains that File Server Resource Manager is needed', dlgText().includes('File Server Resource Manager must be installed'));
    await click('OK');
    ns.back(); await wait(40);
    ns.page._el.querySelector('[data-profile="smb-quick"]').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true })); await wait(20);
    await ns.next(); await wait(40);
    t('Share Location lists the formatted volumes, with F: selected', pageText(ns).includes('Online') && pageText(ns).includes('C:') && pageText(ns).includes('F:') && nsd.volume === 'F' && !pageText(ns).includes('\\\\?\\'));
    if (stop('nslocation')) return;
    await ns.next(); await wait(40);
    ns.next(); await wait(80);
    t('a share name is required', dlgText().includes('Type a share name.'));
    await click('OK');
    type(fieldIn(ns.page._el, 'share-name'), 'Projects'); type(fieldIn(ns.page._el, 'share-desc'), 'Project files');
    t('the paths follow the name', fieldIn(ns.page._el, 'local-path').value === 'F:\\Shares\\Projects' && fieldIn(ns.page._el, 'remote-path').value === `\\\\${name()}\\Projects` && pageText(ns).includes('If the folder does not exist, the folder is created.'));
    if (stop('nsname')) return;
    await ns.next(); await wait(40);
    t('Other Settings: caching on, the rest off, BranchCache unavailable', !fieldIn(ns.page._el, 'abe').checked && fieldIn(ns.page._el, 'caching').checked && !fieldIn(ns.page._el, 'encrypt').checked && fieldIn(ns.page._el, 'branchcache').disabled);
    tick(fieldIn(ns.page._el, 'abe'), true); tick(fieldIn(ns.page._el, 'caching'), false); tick(fieldIn(ns.page._el, 'encrypt'), true);
    if (stop('nssettings')) return;
    await ns.next(); await wait(40);
    t('Permissions: Everyone Full Control on the share, the inherited folder permissions', pageText(ns).includes('Share permissions:Everyone Full Control') && ns.page._el.querySelectorAll('.lv-row').length === 5 && pageText(ns).includes('CREATOR OWNER'));
    if (stop('nsperms')) return;
    let adv = null, getEd = null;
    fieldIn(ns.page._el, 'customize').click(); await wait(80);
    t('Customize permissions opens Advanced Security Settings', dlgText().includes('Advanced Security Settings for Projects') && dlgText().includes('Permission entries:'));
    [...shade().querySelectorAll('.ps-tab')].find(x => x.textContent === 'Share').click(); await wait(40);
    t('its Share tab shows the network location and the share permissions', dlgText().includes(`Network location for this share: \\\\${name()}\\Projects`) && dlgText().includes('Everyone'));
    if (stop('nsadvsec')) return;
    t('the Share tab uses the Shared Folders permission editor', !!shade().querySelector('[data-field="perm-add"]'));
    // remove Everyone, add Administrators with Full Control
    shade().querySelector('[data-field="perm-remove"]').click(); await wait(20);
    const pickerDone = (async () => { shade().querySelector('[data-field="perm-add"]').click(); })(); await wait(120);
    shade().querySelector('.op-box').textContent = 'Administrators'; await wait(10);
    await click('OK'); await wait(80); await pickerDone;
    shade().querySelector('[data-field="perm-Full-Allow"]').click(); await wait(20);
    await click('OK'); await wait(80);
    t('the new share permissions show on the page', /Share permissions:(\S+\\)?Administrators Full Control/.test(pageText(ns)) && !pageText(ns).includes('Everyone Full Control'), pageText(ns).slice(0, 300));
    await ns.next(); await wait(40);
    t('Confirmation summarizes the share', ['Local path:F:\\Shares\\Projects', 'Share name:Projects', 'Protocol:SMB', 'Access-based enumeration:Enabled', 'Caching:Disabled', 'BranchCache:Disabled', 'Encrypt data:Enabled'].every(x => pageText(ns).includes(x)), pageText(ns));
    wzButton(ns, 'Create').click(); await wait(400);
    const sh = WS.smb.get('Projects');
    t('Results reports the share was created', ns.page.id === 'results' && pageText(ns).includes('The share was successfully created.') && pageText(ns).includes('Create SMB share') && pageText(ns).includes('Set SMB permissions'));
    t('the share is made through WS.smb, with its folder', !!sh && sh.path === 'F:\\Shares\\Projects' && WS.fs.isDir('F:\\Shares\\Projects') && sh.description === 'Project files');
    t('its settings and permissions are kept', sh.folderEnumerationMode === 'AccessBased' && sh.cachingMode === 'None' && sh.encryptData === true && sh.access.length === 1 && /Administrators$/.test(sh.access[0].account) && sh.access[0].right === 'Full');
    t('the first share installs the File Server role service', WS.features.isInstalled('FS-FileServer'));
    t('the lab share helper checks the new settings', check({ share: { name: 'Projects', folderEnumerationMode: 'AccessBased', encryptData: true, cachingMode: 'None' } }) && !check({ share: { name: 'Projects', encryptData: false } }));
    t('Get-SmbShare reports EncryptData', (await run('Get-SmbShare -Name Projects'))[0].EncryptData === true && (await run('Get-SmbShare -Name Projects'))[0].FolderEnumerationMode === 'AccessBased');
    if (stop('nsresults')) return;
    wzButton(ns, 'Close').click(); await wait(40);

    /* ---------------- shares ---------------- */
    win.sm.go('fss:shares'); await wait(50);
    t('Shares lists the new share, not the administrative ones', tileText('SHARES').includes('Projects') && tileText('SHARES').includes('F:\\Shares\\Projects') && !tileText('SHARES').includes('C$') && !tileText('SHARES').includes('ADMIN$') && tileText('SHARES').includes('Not Clustered'));
    t('the share the wizard made is selected, with its volume', WS.smfss.selection.shares === 'share:Projects' && tileText('VOLUME').includes('F: on') && tileText('VOLUME').includes('% Used') && tileText('VOLUME').includes('Go to Volumes Overview >'));
    t('without File Server Resource Manager, Quota says how to get it', tileText('QUOTA').includes('File Server Resource Manager must be installed'));
    if (stop('shares')) return;
    [...win.el.querySelectorAll('[data-tile="VOLUME"] a.lnk')].find(a => a.textContent.includes('Go to Volumes Overview')).click(); await wait(50);
    t('Go to Volumes Overview opens Volumes on that volume', win.sm.page === 'fss:volumes' && WS.smfss.selection.volumes === `vol:1:${S.byLetter('F').part.number}` && tileText('SHARES').includes('Projects') && tileText('SHARES').includes('Related Shares | 1 total'));
    let sp = null, api = null;
    busy = WS.sm.shareProperties('Projects', { onCreate: (fr, a) => { sp = fr; api = a; } }); await wait(60);
    t('share Properties opens on General', dlgText().includes('Projects Properties') && dlgText().includes('Folder path:F:\\Shares\\Projects') && dlgText().includes('Availability type:Not Clustered'));
    if (stop('shareprops')) return;
    type(fieldIn(sp.body, 'share-desc'), 'Engineering projects');
    api.show('settings'); await wait(20);
    t('Settings shows the share settings', fieldIn(sp.body, 'abe').checked && !fieldIn(sp.body, 'caching').checked && fieldIn(sp.body, 'encrypt').checked);
    tick(fieldIn(sp.body, 'encrypt'), false); tick(fieldIn(sp.body, 'caching'), true);
    api.apply(); await wait(30);
    t('Apply saves through WS.smb', WS.smb.get('Projects').description === 'Engineering projects' && WS.smb.get('Projects').encryptData === false && WS.smb.get('Projects').cachingMode === 'Manual' && !!shade());
    api.show('perms'); await wait(20);
    t('Permissions shows the share permissions', /Share permissions:(\S+\\)?Administrators Full Control/.test(dlgText()));
    api.ok(); await wait(40); await busy;
    t('OK closes the dialog', !shade());
    busy = WS.smfss.stopSharing('Projects'); await wait(60);
    t('Stop Sharing asks first', dlgText().includes('Are you sure you want to stop sharing Projects?'));
    await click('Yes'); await busy; await wait(40);
    win.sm.go('fss:shares'); await wait(40);
    t('the share is removed, and the empty list offers the New Share Wizard', !WS.smb.get('Projects') && tileText('SHARES').includes('There are no shares.') && tileText('SHARES').includes('start the New Share Wizard'));
    t('the folder stays', WS.fs.isDir('F:\\Shares\\Projects'));
    if (stop('empty')) return;

    /* a custom path; duplicate names */
    ns = null;
    WS.sm.newShare({ onCreate: (w, d) => { ns = w; nsd = d; } }); await wait(80);
    await ns.next(); await wait(40);
    fieldIn(ns.page._el, 'by-path').click(); type(fieldIn(ns.page._el, 'custom-path'), 'Q:\\Nope');
    ns.next(); await wait(80);
    t('a path on a missing drive is refused', dlgText().includes('is not valid'));
    await click('OK');
    type(fieldIn(ns.page._el, 'custom-path'), 'C:\\Data\\Public'); await ns.next(); await wait(40);
    t('a custom path names the share after its folder', fieldIn(ns.page._el, 'share-name').value === 'Public' && fieldIn(ns.page._el, 'local-path').value === 'C:\\Data\\Public');
    WS.smb.newShare({ name: 'Taken', path: 'C:\\' }); await wait(10);
    type(fieldIn(ns.page._el, 'share-name'), 'Taken'); ns.next(); await wait(80);
    t('a share name in use is refused', dlgText().includes('is already in use'));
    await click('OK');
    type(fieldIn(ns.page._el, 'share-name'), 'Public');
    await ns.next(); await wait(30); await ns.next(); await wait(30); await ns.next(); await wait(30);
    wzButton(ns, 'Create').click(); await wait(400);
    t('the folder is created and shared (Everyone Full Control by default)', WS.fs.isDir('C:\\Data\\Public') && WS.smb.get('Public').path === 'C:\\Data\\Public' && WS.smb.get('Public').access[0].account === 'Everyone' && WS.smb.get('Public').access[0].right === 'Full' && WS.smb.get('Public').cachingMode === 'Manual');
    wzButton(ns, 'Close').click(); await wait(40);
    WS.smb.removeShare('Taken');

    /* ---------------- reset, a new offline disk, iSCSI and Work Folders ---------------- */
    win.sm.go('fss:disks'); await wait(40);
    busy = WS.smfss.resetDisk(1); await wait(60);
    t('Reset Disk warns that it erases the disk', dlgText().includes('erases all data'));
    await click('Yes'); await busy; await wait(30);
    t('the disk is uninitialized again and F: is gone', S.disk(1).style === 'RAW' && !S.volume('F') && !R.volumes().some(r => r.volume === 'F:'));
    const n2 = S.addDisk(10); await wait(30);
    t('a new disk follows the SAN policy and arrives offline', !S.disk(n2).online && tileText('DISKS').includes('All disks | 3 total'));
    nv = null;
    WS.sm.newVolume({ disk: n2, onCreate: (w, d) => { nv = w; nvd = d; } }); await wait(80);
    await nv.next(); await wait(30);
    nv.next(); await wait(80);
    t('an offline blank disk is brought online and initialized', dlgText().includes('The selected disk will be brought online and initialized as a GPT disk.'));
    await click('OK'); await wait(60);
    t('it is online and GPT', S.disk(n2).online && S.disk(n2).style === 'GPT');
    await nv.next(); await wait(30); await nv.next(); await wait(30); await nv.next(); await wait(30);
    wzButton(nv, 'Create').click(); await wait(400);
    const e = S.volume('E');
    t('the defaults make an NTFS "New Volume" on E: using the whole disk', !!e && e.fs === 'NTFS' && e.label === 'New Volume' && e.disk === n2 && S.freeRegions(n2).length === 0 && !e.shortNames, e);
    wzButton(nv, 'Close').click(); await wait(30);
    win.sm.go('fss:iscsi'); await wait(40);
    t('iSCSI explains that iSCSI Target Server must be installed', tileText('iSCSI VIRTUAL DISKS').includes('you must install iSCSI Target Server') && tileText('iSCSI VIRTUAL DISKS').includes('start the Add Roles and Features Wizard'));
    win.sm.go('fss:workfolders'); await wait(40);
    t('Work Folders explains that Work Folders must be installed', tileText('WORK FOLDERS').includes('you must install Work Folders'));
    WS.features.install(['FS-iSCSITarget-Server']); await wait(40);
    win.sm.go('fss:iscsi'); await wait(40);
    t('with the role service installed, iSCSI offers its wizard', tileText('iSCSI VIRTUAL DISKS').includes('There are no iSCSI virtual disks.'));
  } catch (e) {
    t('no exception', false, e.stack || e.message);
  }
  console.log(`RESULT ${pass} passed, ${fail} failed`);
})();
