/* Group Policy: the GPO model, policy processing, GPMC, the Group Policy Management Editor, gpupdate/gpresult and the
 * GroupPolicy PowerShell module. Use a fresh profile (it rewrites the lab state).
 * &shot=<mode> stops at that point for a screenshot (modes are listed where they occur). */
(async function () {
  'use strict';
  const WS = window.WS, G = WS.gpo;
  let pass = 0, fail = 0;
  const t = (name, ok, detail) => { ok ? pass++ : fail++; console.log(`${ok ? 'PASS' : 'FAIL'} ${name}${!ok && detail !== undefined ? ' :: ' + JSON.stringify(detail) : ''}`); };
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const shade = () => [...document.querySelectorAll('#dialogs .dlg-shade')].pop();
  const dlgText = () => (shade() ? shade().textContent : '');
  const title = () => (shade() ? shade().querySelector('.dlg-ttext').textContent : '');
  const button = (label, scope = shade()) => [...scope.querySelectorAll('button')].find(x => x.textContent.trim() === label);
  const click = async (label, scope) => { const b = button(label, scope); if (!b) throw new Error('Missing button: ' + label); b.click(); await wait(70); };
  const input = (key, scope = shade()) => scope.querySelector(`[data-field="${CSS.escape(key)}"]`);
  const fill = (key, value, scope) => {
    const el = input(key, scope); if (!el) throw new Error('Missing field: ' + key);
    if (el.type === 'checkbox' || el.type === 'radio') el.checked = value; else el.value = value;
    el.dispatchEvent(new Event(['checkbox', 'radio'].includes(el.type) || el.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true }));
  };
  const stop = name => { if (new URLSearchParams(location.search).get('shot') !== name) return false; console.log(`RESULT ${pass} passed, ${fail} failed`); return true; };
  const item = (items, name) => { const it = items.find(x => x && x.label && WS.ui.plain(x.label) === name); if (!it) throw new Error('Missing menu item: ' + name + ' in ' + items.filter(x => x && x.label).map(x => WS.ui.plain(x.label)).join('|')); return it; };
  const has = (items, name) => items.some(x => x && x.label && WS.ui.plain(x.label) === name);
  const psc = new WS.term.TextConsole(), ps = new WS.ps.Session({ console: psc });
  const run = async cmd => { const out = []; await ps.execute(cmd, { capture: out }); return out; };
  /** Formatted output plus whatever went to the console (error records, native commands). */
  const runText = async cmd => { psc.clear(); const out = []; await ps.execute(cmd, { capture: out }); return WS.ps.formatOut(out, 120).join('\n') + '\n' + psc.text(); };
  const cmdc = new WS.term.TextConsole(), cmd = new WS.term.CmdSession({ console: cmdc });
  const crun = async line => { cmdc.clear(); await cmd.execute(line); return cmdc.text(); };
  const check = c => WS.labs.evalCheck(c, WS.state);
  const names = list => list.map(e => e.name || (e.gpo && e.gpo.name));
  try {
    await wait(250);

    /* ---------------- workgroup server: the Local Group Policy object ---------------- */
    t('no domain: no GPOs, New GPO fails', G.list().length === 0 && !G.create('Test').ok);
    let r = G.setSetting('local', 'computer', 'MinimumPasswordLength', 10);
    t('local policy: Minimum password length applies to local accounts at once', r.ok && WS.sec.policy().minLength === 10, r);
    t('local policy: a too-short local password is refused', !WS.local.createUser('shorty', { password: 'Ab1!' }).ok);
    G.setSetting('local', 'computer', 'MinimumPasswordLength', 0);
    t('local policy: setting it back to 0 works', WS.sec.policy().minLength === 0);
    r = G.setSetting('local', 'computer', 'MinimumPasswordLength', 15);
    t('Minimum password length is limited to 14 unless relaxed', !r.ok && /between 0 and 14/.test(r.error), r);
    G.setSetting('local', 'computer', 'MinimumPasswordLength', null);

    /* ---------------- promotion creates the default GPOs ---------------- */
    WS.features.install(['AD-Domain-Services'], { includeManagementTools: true });
    const promo = WS.ad.installForest({ domainName: 'contoso.local', safeModePassword: 'RestoreP@ss2025!', noReboot: true });
    t('promotion succeeds', promo.ok, promo);
    const ddp = G.get(G.DDP), ddcp = G.get(G.DDCP);
    t('Default Domain Policy and Default Domain Controllers Policy exist', !!ddp && !!ddcp && G.list().length === 2);
    t('Default Domain Policy is linked to the domain, the DC policy to Domain Controllers', G.links(ddp).map(l => G.somPath(l.som)).join() === 'contoso.local' && G.links(ddcp).map(l => G.somPath(l.som)).join() === 'contoso.local/Domain Controllers');
    t('Default Domain Policy defines the install-time password policy', ddp.computer.MinimumPasswordLength === 7 && ddp.computer.PasswordHistorySize === 24 && ddp.computer.PasswordComplexity === true && ddp.computer.LockoutBadCount === 0);
    t('Default Domain Controllers Policy defines user rights', ddcp.computer.SeInteractiveLogonRight.includes('BUILTIN\\Administrators'));
    t('security filtering: Authenticated Users', G.filtering(ddp).map(p => p.name).join() === 'NT AUTHORITY\\Authenticated Users');
    const dir = G.gpoDir(ddp);
    t('SYSVOL: GPT.INI version 3 and the MACHINE folder', /Version=3/.test(WS.fs.readFile(dir + '\\GPT.INI')) && WS.fs.isDir(dir + '\\MACHINE'));
    t('SYSVOL: GptTmpl.inf holds the password policy', /MinimumPasswordLength = 7/.test(WS.fs.readFile(dir + '\\MACHINE\\Microsoft\\Windows NT\\SecEdit\\GptTmpl.inf')));
    t('older link list migrated away', ddp.links === undefined && WS.ad.root().gpLinks.length === 1);

    /* ---------------- directory for the scenarios ---------------- */
    const A = WS.ad;
    A.createOU({ name: 'Sales' }); A.createOU({ name: 'East', parent: 'Sales' });
    A.createGroup({ name: 'Sales Staff', parent: 'Sales' });
    A.createUser({ name: 'Jo Smith', sam: 'jsmith', parent: 'Sales/East', password: 'Pa$$w0rd123' });
    A.addMember('Sales Staff', 'jsmith');

    /* ---------------- GPOs and links ---------------- */
    r = G.create('Sales Desktop');
    const sd = r.gpo;
    t('New GPO: a GUID, versions 0, the GPMC GPT.INI', r.ok && /^\{[0-9A-F-]{36}\}$/.test(sd.id) && sd.userVersion === 0 && /displayName=New Group Policy Object/.test(WS.fs.readFile(G.gpoDir(sd) + '\\GPT.INI')));
    t('a second GPO with the same name is refused', !G.create('sales desktop').ok);
    r = G.link(sd, 'Sales');
    t('link to the Sales OU', r.ok && r.link.order === 1 && G.somLinks('Sales').length === 1, r);
    t('linking twice is refused', /already linked/.test(G.link(sd, 'Sales').error));
    t('the Users container cannot be linked', /cannot be linked/.test(G.link(sd, A.usersContainerDN()).error));
    r = G.setSetting(sd, 'user', 'NoControlPanel', 'Enabled');
    t('setting a user policy bumps the user version and writes Registry.pol', r.ok && sd.userVersion === 1 && WS.fs.exists(G.gpoDir(sd) + '\\User\\Registry.pol'), r);
    t('display: Enabled; unset policies are Not configured', G.display(G.definition('user', 'NoControlPanel'), sd.user.NoControlPanel) === 'Enabled' && G.display(G.definition('user', 'NoRun'), undefined) === 'Not configured');

    /* ---------------- inheritance ---------------- */
    const inh = som => G.inheritance(som).map(e => `${e.precedence}:${e.gpo.name}`).join('|');
    t('East inherits Sales Desktop, then the Default Domain Policy', inh('Sales/East') === '1:Sales Desktop|2:Default Domain Policy', inh('Sales/East'));
    G.setBlockInheritance('Sales', true);
    t('Block Inheritance on Sales drops the domain GPO', inh('Sales/East') === '1:Sales Desktop' && G.isBlocked('Sales'));
    G.setLink(ddp, 'contoso.local', { enforced: true });
    t('an enforced domain link gets through the block and wins', inh('Sales/East') === '1:Default Domain Policy|2:Sales Desktop');
    G.setLink(ddp, 'contoso.local', { enforced: false }); G.setBlockInheritance('Sales', false);
    const second = G.create('Sales Printers').gpo; G.link(second, 'Sales', { order: 1 });
    t('a new link at order 1 takes precedence', inh('Sales') === '1:Sales Printers|2:Sales Desktop|3:Default Domain Policy');
    G.setLink(second, 'Sales', { order: 2 });
    t('changing the link order', inh('Sales') === '1:Sales Desktop|2:Sales Printers|3:Default Domain Policy');
    G.setLink(second, 'Sales', { enabled: false });
    t('a disabled link is left out of the inheritance list', inh('Sales') === '1:Sales Desktop|2:Default Domain Policy');

    /* ---------------- RSoP ---------------- */
    let rs = G.rsop({ user: 'jsmith' });
    t('RSoP (jsmith): Sales Desktop applies', names(rs.user.applied).includes('Sales Desktop') && rs.user.settings.NoControlPanel.value.state === 'Enabled');
    const reason = (side, n) => (rs[side].filtered.find(e => e.name === n) || {}).reason;
    t('RSoP: the Default Domain Policy has no user settings (Not Applied (Empty))', reason('user', 'Default Domain Policy') === 'Not Applied (Empty)');
    t('RSoP: the disabled link is reported as Disabled (Link)', reason('user', 'Sales Printers') === 'Disabled (Link)');
    t('RSoP (computer): DC policy then domain policy', names(rs.computer.applied).slice(0, 2).join('|') === 'Default Domain Controllers Policy|Default Domain Policy', names(rs.computer.applied));
    t('RSoP: Local Group Policy is empty', reason('computer', 'Local Group Policy') === 'Not Applied (Empty)');
    rs = G.rsop({ user: 'Administrator' });
    t('RSoP (Administrator in CN=Users): only domain-linked GPOs are in scope', !names(rs.user.applied).includes('Sales Desktop') && !rs.user.filtered.some(e => e.name === 'Sales Desktop'));

    /* security filtering and MS16-072 */
    G.setPermission(sd, 'Authenticated Users', 'None', { replace: true });
    G.setPermission(sd, 'Sales Staff', 'GpoApply');
    t('security filtering is now Sales Staff', G.filtering(sd).map(p => p.name).join() === 'CONTOSO\\Sales Staff');
    A.createComputer({ name: 'CLIENT01', parent: 'Sales' });
    rs = G.rsop({ computer: 'CLIENT01', user: 'jsmith' });
    t('on a workstation that cannot read the GPO, the user GPO is Denied (Security) (MS16-072)', reason('user', 'Sales Desktop') === 'Denied (Security)');
    rs = G.rsop({ user: 'jsmith' });
    t('on the DC it still applies: ENTERPRISE DOMAIN CONTROLLERS can read every GPO', names(rs.user.applied).includes('Sales Desktop'));
    G.setPermission(sd, 'Domain Computers', 'GpoRead');
    rs = G.rsop({ computer: 'CLIENT01', user: 'jsmith' });
    t('Domain Computers: Read lets the workstation read it: applies again', names(rs.user.applied).includes('Sales Desktop'));
    G.setPermission(sd, 'Domain Computers', 'None', { replace: true });
    G.setPermission(sd, 'Authenticated Users', 'GpoRead');
    rs = G.rsop({ computer: 'CLIENT01', user: 'jsmith' });
    t('so does Authenticated Users: Read', names(rs.user.applied).includes('Sales Desktop'));
    t('lowering a permission needs replace', !G.setPermission(sd, 'Sales Staff', 'GpoRead').ok && G.setPermission(sd, 'Sales Staff', 'GpoApply').ok);
    const delegation = G.permissions(sd).map(p => `${p.short}=${p.label}`).join('|');
    t('delegation labels', delegation.includes('Sales Staff=Read (from Security Filtering)') && delegation.includes('Authenticated Users=Read') && delegation.includes('Domain Admins=Edit settings, delete, modify security'), delegation);
    G.setStatus(sd, 'UserSettingsDisabled');
    rs = G.rsop({ user: 'jsmith' });
    t('GPO status User configuration settings disabled -> Disabled (GPO)', reason('user', 'Sales Desktop') === 'Disabled (GPO)' && G.statusLabel(sd.status) === 'User configuration settings disabled');
    G.setStatus(sd, 'AllSettingsEnabled');

    /* WMI filters */
    const q = s => G.evalWql(s, G.thisComputer());
    t('WQL: ProductType = 2 is true on the DC', q('SELECT * FROM Win32_OperatingSystem WHERE ProductType = "2"') === true && q('SELECT * FROM Win32_OperatingSystem WHERE ProductType = 3') === false);
    t('WQL: LIKE and AND', q('select * from Win32_OperatingSystem where Caption like "%Server%" and Version like "10.%"') === true);
    t('WQL: an unknown class has no instances; garbage cannot be evaluated', q('SELECT * FROM Win32_Battery') === false && q('SELECT * FROM Win32_OperatingSystem WHERE (') === null);
    r = G.createWmiFilter({ name: 'Member servers only', description: 'Excludes DCs and workstations', queries: ['SELECT * FROM Win32_OperatingSystem WHERE ProductType = "3"'] });
    t('New WMI filter', r.ok && G.wmiFilters().length === 1, r);
    const ws = G.create('Server Baseline').gpo;
    G.setSetting(ws, 'computer', 'DisableAntiSpyware', 'Disabled');
    G.link(ws, 'Domain Controllers');
    G.setGpoWmiFilter(ws, 'Member servers only');
    rs = G.rsop({ user: null });
    t('a WMI filter that is false on the DC -> Denied (WMI Filter)', reason('computer', 'Server Baseline') === 'Denied (WMI Filter)');
    t('a filter in use cannot be deleted', !G.removeWmiFilter('Member servers only').ok);
    G.setGpoWmiFilter(ws, null);

    /* ---------------- processing: the domain password policy ---------------- */
    G.refresh({ reason: 'manual' });
    G.setSetting(ddp, 'computer', 'MinimumPasswordLength', 12);
    t('editing the Default Domain Policy does not change the domain until policy is processed', A.policy().minLength === 7);
    let res = G.refresh({ reason: 'manual' });
    t('gpupdate applies it: minimum length 12', res.computer.changed && A.policy().minLength === 12, res);
    const sys = () => WS.state.events.logs.System.slice(-6).map(e => e.id);
    t('System log: 1502 (new settings applied)', sys().includes(1502));
    t('Application log: SceCli 1704', WS.state.events.logs.Application.slice(-3).some(e => e.id === 1704 && e.source === 'SceCli'));
    res = G.refresh({ reason: 'manual' });
    t('processing again without changes: 1500 (computer) and 1501 (user)', !res.computer.changed && sys().slice(-2).join() === '1500,1501', sys());
    t('Operational log: 5312 lists the applicable GPOs in processing order', WS.state.events.logs['Microsoft-Windows-GroupPolicy/Operational'].some(e => e.id === 5312 && /Default Domain Policy\n(.*\n)?Default Domain Controllers Policy/.test(e.message)));
    G.setSetting(ws, 'computer', 'MinimumPasswordLength', 3); G.refresh();
    t('password policy in an OU-linked GPO does not change the domain policy', A.policy().minLength === 12);
    t('a short domain password is refused now', !A.createUser({ name: 'Short Pw', sam: 'shortpw', password: 'Abcdef1!' }).ok);
    await run('Set-ADDefaultDomainPasswordPolicy -Identity contoso.local -MinPasswordLength 5');
    t('Set-ADDefaultDomainPasswordPolicy writes the domain object', A.policy().minLength === 5);
    G.refresh();
    t('a normal refresh (nothing changed in the GPOs) leaves it', A.policy().minLength === 5);
    G.refresh({ force: true });
    t('a forced refresh re-applies the Default Domain Policy', A.policy().minLength === 12);
    G.setSetting(ddp, 'computer', 'LockoutBadCount', 5); G.setSetting(ddp, 'computer', 'LockoutDuration', 15); G.setSetting(ddp, 'computer', 'ResetLockoutCount', 15);
    G.refresh();
    t('account lockout settings reach the domain policy', A.policy().lockoutThreshold === 5 && A.policy().lockoutMinutes === 15 && A.policy().lockoutWindowMinutes === 15);
    const pol = (await run('Get-ADDefaultDomainPasswordPolicy'))[0];
    t('Get-ADDefaultDomainPasswordPolicy shows them', pol.LockoutThreshold === 5 && pol.LockoutDuration === '00:15:00' && pol.LockoutObservationWindow === '00:15:00' && pol.MinPasswordLength === 12, pol);
    t('display: lockout duration is Not Applicable while the threshold is 0', G.display(G.definition('computer', 'LockoutDuration'), undefined, { computer: { LockoutBadCount: 0 } }) === 'Not Applicable');

    /* ---------------- registry values (Set-GPRegistryValue) ---------------- */
    r = G.setRegistryValue(sd, { key: 'HKCU\\Software\\Policies\\Microsoft\\Windows\\System', valueName: 'DisableCMD', type: 'DWord', value: 1 });
    t('a registry value with an ADMX policy becomes that policy', r.ok && sd.user.DisableCMD.state === 'Enabled' && sd.user.DisableCMD.options.DisableCMD === 1, sd.user.DisableCMD);
    G.setRegistryValue(sd, { key: 'HKCU\\Software\\Contoso\\App', valueName: 'Theme', type: 'String', value: 'Dark' });
    t('other values are kept as Extra Registry Settings', sd.registry.user.length === 1 && G.registryValues(sd).some(v => v.value === 'Theme' && v.data === 'Dark'));
    t('the GPO report lists Extra Registry Settings', G.reportBody(sd).includes('Extra Registry Settings'));
    r = G.removeRegistryValue(sd, 'HKCU\\Software\\Contoso\\App', 'Theme');
    t('Remove-GPRegistryValue', r.ok && !sd.registry.user.length);

    /* ---------------- reports ---------------- */
    const html = G.reportHtml(ddp);
    t('GPO report: General, links, password settings', html.includes('Default Domain Policy') && html.includes('Account Policies/Password Policy') && html.includes('12 characters') && html.includes('Computer Configuration (Enabled)'));
    t('XML report', /<Name>Default Domain Policy<\/Name>/.test(G.reportXml(ddp)) && /<SOMPath>contoso.local<\/SOMPath>/.test(G.reportXml(ddp)));
    const rh = G.rsopHtml(G.rsop({ user: 'jsmith' }));
    t('RSoP report: applied and denied GPOs, winning GPO', rh.includes('Applied GPOs') && rh.includes('Denied GPOs') && rh.includes('Winning GPO') && rh.includes('Sales Desktop'));

    /* ---------------- copy, backup, restore ---------------- */
    r = G.copy(ddp);
    t('Copy of Default Domain Policy has the same settings and no links', r.ok && r.gpo.name === 'Copy of Default Domain Policy' && r.gpo.computer.MinimumPasswordLength === 12 && !G.links(r.gpo).length);
    G.remove(r.gpo);
    t('backup to a missing folder fails', /cannot find the path/.test(G.backup('all', 'C:\\GPOBackup').error));
    WS.fs.ensureDir('C:\\GPOBackup');
    r = G.backup('all', 'C:\\GPOBackup', 'Before the lab');
    t('Back Up All writes one folder per GPO', r.ok && r.backups.length === G.list().length && G.backups('C:\\GPOBackup').length === G.list().length, r);
    const sdBackup = G.backups('C:\\GPOBackup').find(b => b.name === 'Sales Desktop');
    t('bkupInfo.xml records the GPO name, GUID and comment', sdBackup && sdBackup.gpoId === sd.id && sdBackup.comment === 'Before the lab');
    G.remove(sd);
    t('deleting a GPO removes its links and SYSVOL folder', !G.get('Sales Desktop') && !G.somLinks('Sales').some(l => l.gpo === sd.id) && !WS.fs.exists(G.gpoDir(sd)));
    r = G.restore(sdBackup.backupId, 'C:\\GPOBackup');
    const back = G.get('Sales Desktop');
    t('Restore-GPO re-creates it with the same GUID and settings, but not its links', r.ok && back && back.id === sd.id && back.user.NoControlPanel.state === 'Enabled' && !G.links(back).length, r);
    G.link(back, 'Sales');
    r = G.importSettings(sdBackup.backupId, 'C:\\GPOBackup', 'Imported', { createIfNeeded: true });
    t('Import-GPO into a new GPO', r.ok && G.get('Imported').user.NoControlPanel.state === 'Enabled' && G.get('Imported').id !== sd.id);
    G.remove('Imported');

    /* ---------------- Starter GPOs and dcgpofix ---------------- */
    t('Starter GPOs folder: two system Starter GPOs', G.createStarterFolder().ok && G.starters().length === 2 && G.starters().every(s => s.system));
    r = G.createStarter('Kiosk Lockdown', 'Locked-down desktops');
    G.setStarterSetting('Kiosk Lockdown', 'user', 'NoRun', 'Enabled');
    r = G.create('Kiosk Users', { starter: 'Kiosk Lockdown' });
    t('New GPO from a Starter GPO copies its Administrative Templates', r.ok && r.gpo.user.NoRun.state === 'Enabled');
    t('Starter GPOs refuse security settings', !G.setStarterSetting('Kiosk Lockdown', 'computer', 'MinimumPasswordLength', 9).ok);
    G.remove('Kiosk Users');
    G.remove(ddcp);
    r = G.restoreDefaults('dc');
    t('dcgpofix re-creates the Default Domain Controllers Policy, linked again', r.ok && G.get(G.DDCP) && G.links(G.get(G.DDCP)).length === 1 && G.get(G.DDCP).computer.SeInteractiveLogonRight.length > 0, r);

    /* ================================================================ GPMC */
    t('gpmc.msc and gpedit.msc are registered', !!WS.apps.get('gpmc') && !!WS.apps.get('gpedit') && !!WS.term.native('gpmc.msc') && !!WS.term.native('gpedit.msc'));
    t('Server Manager Tools lists Group Policy Management (installed with the AD DS tools)', WS.features.isInstalled('GPMC'));
    const win = WS.apps.launch('gpmc'), ctl = win.gpmc, mmc = ctl.mmc;
    await wait(120);
    const pane = () => win.el.querySelector('.mmc-rbody');
    const tabs = () => [...pane().querySelectorAll('.gpmc-tab')].map(x => x.textContent);
    const treeText = () => win.el.querySelector('.mmc-tree').textContent;
    t('opens on the domain: Status, Linked Group Policy Objects, Group Policy Inheritance, Delegation', mmc.current().id === 'gpmc-som:' + A.root().id && tabs().join('|') === 'Status|Linked Group Policy Objects|Group Policy Inheritance|Delegation', tabs());
    t('tree: Forest, Domains, contoso.local, Group Policy Objects, WMI Filters, Starter GPOs, Sites, Modeling, Results', ['Forest: contoso.local', 'Domains', 'Default Domain Policy', 'Domain Controllers', 'Sales', 'Group Policy Objects', 'WMI Filters', 'Starter GPOs', 'Sites', 'Group Policy Modeling', 'Group Policy Results'].every(x => treeText().includes(x)));
    ctl.tab('Linked Group Policy Objects'); await wait(40);
    t('domain: Linked GPOs lists the Default Domain Policy at link order 1', ctl.linkedList.rows().length === 1 && pane().textContent.includes('Default Domain Policy'));
    if (stop('gpmc')) return;
    ctl.tab('Group Policy Inheritance'); await wait(30);
    t('domain: inheritance is just the Default Domain Policy', ctl.inheritanceList.rows().map(r => r.gpo.name).join() === 'Default Domain Policy');

    const sales = G.somOf('Sales'), east = G.somOf('Sales/East'), back2 = G.get('Sales Desktop'), printers = G.get('Sales Printers');
    ctl.open('gpmc-som:' + sales.id); await wait(60);
    t('an OU has Linked Group Policy Objects, Group Policy Inheritance, Delegation', tabs().join('|') === 'Linked Group Policy Objects|Group Policy Inheritance|Delegation', tabs());
    ctl.tab('Linked Group Policy Objects'); await wait(30);
    const order = () => ctl.linkedList.rows().slice().sort((a, b) => a.order - b.order).map(r => r.gpoObj.name).join();
    t('Sales lists Sales Printers (disabled) then Sales Desktop', order() === 'Sales Printers,Sales Desktop' && ctl.linkedList.rows().find(r => r.gpo === printers.id).enabled === false, order());
    ctl.linkedList.select([back2.id]); await wait(20);
    pane().querySelector('[data-move="up"]').click(); await wait(60);
    t('the Move link up arrow changes the link order', order() === 'Sales Desktop,Sales Printers', order());
    mmc.tree.expand('gpmc-som:' + sales.id); await wait(30);
    t('the tree shows links before child OUs', treeText().indexOf('Sales Desktop') > 0 && treeText().indexOf('Sales Desktop') < treeText().indexOf('East'));

    /* link node: the warning, then Scope / Details / Settings / Delegation / Status */
    let notice = null; ctl.onNotice = f => { notice = f; };
    ctl.open(`gpmc-link:${sales.id}:${back2.id}`); await wait(100);
    t('selecting a link shows the link warning', !!notice && dlgText().includes('You have selected a link to a Group Policy Object (GPO). Except for changes to link properties'));
    if (stop('notice')) return;
    fill('dontshow', true); await click('OK');
    t('"Do not show this message again" is remembered', WS.state.gp.prefs.noLinkNotice === true);
    t('a GPO has Scope, Details, Settings, Delegation, Status', tabs().join('|') === 'Scope|Details|Settings|Delegation|Status', tabs());
    ctl.tab('Scope'); await wait(40);
    t('Scope: links (Sales) and security filtering (Sales Staff)', ctl.scope.links.rows().some(r => r.som.id === sales.id) && ctl.scope.filtering.rows().map(r => r.short).join() === 'Sales Staff');
    if (stop('scope')) return;
    await WS.gpmc.addFiltering(back2, { picked: [{ principal: 'CONTOSO\\Domain Users', name: 'Domain Users' }] }); await wait(60);
    t('Security Filtering Add... grants Apply', G.filtering(back2).some(p => p.short === 'Domain Users') && ctl.scope.filtering.rows().length === 2);
    ctl.scope.filtering.select([G.resolvePrincipal('Domain Users').sid]); ctl.scope.removeFilter(); await wait(60);
    t('Remove asks "Do you want to remove this delegation privilege?"', dlgText().includes('Do you want to remove this delegation privilege?'));
    await click('OK'); await wait(40);
    t('...and removes it', !G.filtering(back2).some(p => p.short === 'Domain Users'));
    const mso = G.wmiFilter('Member servers only');
    ctl.scope.wmi.value = mso.id; ctl.scope.wmi.dispatchEvent(new Event('change', { bubbles: true })); await wait(60);
    t('choosing a WMI filter asks first', dlgText().includes('Do you want to change the WMI filter to Member servers only?'));
    await click('Yes'); await wait(40);
    t('...and links it', back2.wmiFilter === mso.id);
    ctl.scope.wmi.value = ''; ctl.scope.wmi.dispatchEvent(new Event('change', { bubbles: true })); await wait(60); await click('Yes'); await wait(30);
    t('<none> clears it', back2.wmiFilter === null);
    ctl.tab('Details'); await wait(30);
    t('Details: owner, versions, Unique ID', pane().textContent.includes('Domain Admins (CONTOSO\\Domain Admins)') && pane().textContent.includes(back2.id) && pane().textContent.includes(`${back2.userVersion} (AD), ${back2.userVersion} (SYSVOL)`));
    fill('gpoStatus', 'UserSettingsDisabled', pane()); await wait(40);
    t('the GPO Status drop-down changes the status', back2.status === 'UserSettingsDisabled');
    G.setStatus(back2, 'AllSettingsEnabled'); await wait(40);
    ctl.tab('Settings'); await wait(40);
    t('Settings: the report with User Configuration and the policy', pane().textContent.includes('User Configuration (Enabled)') && pane().textContent.includes('Prohibit access to Control Panel and PC settings') && pane().textContent.includes('Security Filtering'));
    const sec1 = pane().querySelector('.gp-sec'); sec1.querySelector('[data-gprep-toggle]').click(); await wait(20);
    t('report sections hide and show', sec1.classList.contains('closed') && sec1.querySelector('.gp-tog').textContent === 'show');
    if (stop('settings')) return;
    ctl.tab('Delegation'); await wait(30);
    let addDlg = WS.gpmc.addDelegation(back2, { picked: [{ principal: 'CONTOSO\\Domain Admins', name: 'Domain Admins' }] }); await wait(50);
    t('Delegation Add...: Add Group or User', title() === 'Add Group or User');
    await click('OK'); await addDlg;
    t('Domain Admins already had more than Read: the level is replaced with the chosen one', G.permissions(back2).find(p => p.short === 'Domain Admins').level === 'GpoRead');
    G.setPermission(back2, 'Domain Admins', 'GpoEditDeleteModifySecurity', { replace: true });

    /* menus and dialogs */
    const lm = WS.gpmc.linkMenu(sales, back2, ctl);
    t('link menu: Edit..., Enforced, Link Enabled, Save Report..., Delete, Rename', ['Edit...', 'Enforced', 'Link Enabled', 'Save Report...', 'Delete', 'Rename'].every(x => has(lm, x)));
    item(lm, 'Enforced').action(); await wait(30);
    t('Enforced from the link menu', G.somLinks(sales).find(l => l.gpo === back2.id).enforced);
    G.setLink(back2, sales, { enforced: false });
    const gm = WS.gpmc.gpoMenu(back2, ctl);
    t('GPO menu: GPO Status, Back Up..., Restore from Backup..., Import Settings..., Copy', ['GPO Status', 'Back Up...', 'Restore from Backup...', 'Import Settings...', 'Save Report...', 'Copy', 'Delete', 'Rename'].every(x => has(gm, x)));
    const om = WS.gpmc.somMenu(east, ctl);
    t('OU menu: Create a GPO..., Link an Existing GPO..., Block Inheritance, Group Policy Update...', ['Create a GPO in this domain, and Link it here...', 'Link an Existing GPO...', 'Block Inheritance', 'Group Policy Update...', 'Group Policy Modeling Wizard...', 'New Organizational Unit'].every(x => has(om, x)));
    let busy = WS.gpmc.newGpo({ link: east }); await wait(60);
    t('New GPO: "New Group Policy Object", Source Starter GPO (none)', title() === 'New GPO' && input('name').value === 'New Group Policy Object' && input('starter').value === '');
    fill('name', 'East Wallpaper'); await click('OK'); await busy; await wait(40);
    const ew0 = G.get('East Wallpaper');
    t('Create a GPO in this domain, and Link it here... creates and links it', !!ew0 && G.links(ew0).some(l => l.som.id === east.id));
    busy = WS.gpmc.newGpo(); await wait(40); fill('name', 'east wallpaper'); await click('OK');
    t('a duplicate name is refused', dlgText().includes('already exists'));
    await click('OK'); await click('Cancel'); await busy;
    let sel = null;
    busy = WS.gpmc.linkExisting(east, { onCreate: api => { sel = api; } }); await wait(50);
    t('Select GPO lists the domain GPOs', title() === 'Select GPO' && sel.list.rows().length === G.list().length);
    sel.select('Server Baseline'); await click('OK'); await busy;
    t('Link an Existing GPO', G.somLinks(east).some(l => l.gpoObj.name === 'Server Baseline'));
    busy = WS.gpmc.deleteLink(east, G.get('Server Baseline')); await wait(40);
    t('deleting a link: "This will not delete the GPO itself."', dlgText().includes('Do you want to delete this link? This will not delete the GPO itself.'));
    await click('OK'); await busy;
    t('the link is gone, the GPO stays', !G.somLinks(east).some(l => l.gpoObj.name === 'Server Baseline') && !!G.get('Server Baseline'));
    item(WS.gpmc.somMenu(east, ctl), 'Block Inheritance').action(); await wait(40);
    t('Block Inheritance from the OU menu', G.isBlocked(east) && item(WS.gpmc.somMenu(east, ctl), 'Block Inheritance').checked);
    G.setBlockInheritance(east, false);
    busy = WS.gpmc.remoteUpdate(G.somOf('Domain Controllers')); await wait(40);
    t('Group Policy Update... asks first', dlgText().includes('Are you sure you want to update the policy on the following computers?'));
    await click('OK'); await wait(80);
    t('Remote Group Policy update results: this DC Succeeded', title() === 'Remote Group Policy update results' && dlgText().includes(WS.sys.name) && dlgText().includes('Succeeded'), [title(), dlgText().slice(0, 300)]);
    await click('Close'); await busy;
    WS.fs.ensureDir('C:\\Reports');
    await WS.gpmc.saveReport('gpo', ddp, { path: 'C:\\Reports\\ddp.htm' });
    t('Save Report... writes the HTML report', /<title>Default Domain Policy<\/title>/.test(WS.fs.readFile('C:\\Reports\\ddp.htm')) && WS.fs.readFile('C:\\Reports\\ddp.htm').includes('Password Policy'));
    busy = WS.gpmc.backupDialog(ew0, { path: 'C:\\GPOBackup' }); await wait(40);
    t('Back Up Group Policy Object dialog', title() === 'Back Up Group Policy Object' && input('location').value === 'C:\\GPOBackup');
    fill('description', 'UI backup'); await click('Back Up'); await wait(60);
    t('the Backup dialog reports success', dlgText().includes('East Wallpaper: Succeeded'));
    await click('OK'); await busy;
    G.remove(ew0);
    let mb = null;
    busy = WS.gpmc.manageBackups({ path: 'C:\\GPOBackup', onCreate: api => { mb = api; } }); await wait(60);
    const ewb = mb.list.rows().find(b => b.name === 'East Wallpaper');
    t('Manage Backups lists the latest backup of each GPO', !!ewb && ewb.comment === 'UI backup' && new Set(mb.list.rows().map(b => b.gpoId)).size === mb.list.rows().length);
    mb.list.select([ewb.backupId]); const restoring = mb.restore(); await wait(50);
    await click('OK'); await wait(60); await click('OK'); await restoring;
    t('Restore brings the deleted GPO back (without its link)', !!G.get('East Wallpaper') && !G.links(G.get('East Wallpaper')).length);
    await click('Close'); await busy;
    WS.gpmc.clipboard.gpo = ddp.id;
    t('Paste appears on Group Policy Objects after Copy', has(mmc.tree.node('gpmc-gpos') ? mmc.tree.node('gpmc-gpos').menu() : [], 'Paste'));
    busy = WS.gpmc.pasteGpo(); await wait(40);
    t('Copy GPO: default or preserved permissions', title() === 'Copy GPO');
    fill('preservePerms', true); await click('OK'); await busy;
    t('the copy exists', !!G.get('Copy of Default Domain Policy'));
    let wfapi = null, qd = null;
    busy = WS.gpmc.wmiFilterDialog(null, { onCreate: api => { wfapi = api; }, onQuery: f => { qd = f; } }); await wait(50);
    fill('name', 'Domain controllers'); fill('description', 'ProductType 2');
    const adding = wfapi.add(); await wait(50);
    t('WMI Query dialog: namespace root\\CIMv2', title() === 'WMI Query' && input('namespace').value === 'root\\CIMv2');
    fill('query', 'SELECT * FROM Win32_OperatingSystem WHERE ProductType = "2"'); await click('OK'); await adding;
    await click('Save'); await busy;
    t('New WMI Filter saved with its query', G.wmiFilters().some(f => f.name === 'Domain controllers' && /ProductType = "2"/.test(f.queries[0].query)));
    ctl.open('gpmc-starters'); await wait(50);
    t('Starter GPOs lists the system and custom Starter GPOs', pane().textContent.includes('Group Policy Reporting Firewall Ports') && pane().textContent.includes('Kiosk Lockdown'));

    /* Group Policy Results and Modeling */
    let wz = null;
    busy = WS.gpmc.resultsWizard({ console: ctl, onCreate: w => { wz = w; } }); await wait(80);
    t('Group Policy Results Wizard opens on its welcome page', title() === 'Group Policy Results Wizard' && wz.el.textContent.includes('Welcome to the Group Policy Results Wizard'));
    for (let i = 0; i < 4; i++) { wz.next(); await wait(40); }
    t('summary page reached', wz.page.id === 'done');
    await click('Finish', wz.el); await busy; await wait(100);
    t('the result node opens: Administrator on <server>', mmc.current().id.startsWith('gpmc-result:') && pane().textContent.includes(`Administrator on ${WS.sys.name}`), [mmc.current().id, pane().textContent.slice(0, 120)]);
    t('Summary: applied GPOs and component status', pane().textContent.includes('Applied GPOs') && pane().textContent.includes('Default Domain Controllers Policy') && pane().textContent.includes('Group Policy Infrastructure'));
    t('Results tabs: Summary, Settings, Policy Events', tabs().join('|') === 'Summary|Settings|Policy Events');
    if (stop('results')) return;
    ctl.tab('Settings'); await wait(40);
    t('Settings: Winning GPO', pane().textContent.includes('Winning GPO') && pane().textContent.includes('Account Policies/Password Policy'));
    busy = WS.gpmc.modelingWizard({ console: ctl, onCreate: w => { wz = w; } }); await wait(80);
    wz.next(); await wait(40); wz.next(); await wait(40);
    fill('userObject', true, wz.el); fill('userText', 'jsmith', wz.el); fill('computerObject', true, wz.el); fill('computerText', 'CLIENT01', wz.el);
    wz.next(); await wait(40); wz.next(); await wait(40); wz.next(); await wait(40);
    await click('Finish', wz.el); await busy; await wait(100);
    t('Group Policy Modeling: Jo Smith on CLIENT01 applies Sales Desktop', pane().textContent.includes('Jo Smith on CLIENT01') && pane().textContent.includes('Sales Desktop'));
    t('Modeling tabs: Summary, Settings, Query', tabs().join('|') === 'Summary|Settings|Query');

    /* ================================================================ Group Policy Management Editor */
    const edw = WS.gpme.open(ddp), ec = edw.gpme, emmc = ec.mmc;
    await wait(100);
    t('editor root: Default Domain Policy [<DC FQDN>] Policy', edw.el.textContent.includes(`Default Domain Policy [${WS.sys.fqdn().toUpperCase()}] Policy`), edw.el.querySelector('.mmc-tree').textContent.slice(0, 160));
    ec.open('gpme:c.sec.pw'); await wait(60);
    t('Password Policy: eight settings with their values', emmc.list.rows().length === 8 && edw.el.textContent.includes('12 characters') && edw.el.textContent.includes('24 passwords remembered'));
    if (stop('editor')) return;
    let sh = null, sui = null;
    busy = WS.gpme.securityDialog(ddp, 'computer', 'MinimumPasswordLength', { onCreate: (s2, u) => { sh = s2; sui = u; } }); await wait(60);
    t('Minimum password length Properties: Security Policy Setting and Explain', title() === 'Minimum password length Properties' && dlgText().includes('Security Policy Setting') && dlgText().includes('Explain') && dlgText().includes('Password must be at least:'));
    fill('value', '20'); sh.ok(); await wait(60);
    t('out of range is refused', dlgText().includes('between 0 and 14'));
    await click('OK'); fill('value', '14'); sh.ok(); await busy;
    t('OK saves it in the GPO', ddp.computer.MinimumPasswordLength === 14);
    const lt = G.create('Lockout Test').gpo;
    busy = WS.gpme.securityDialog(lt, 'computer', 'LockoutBadCount', { onCreate: (s2, u) => { sh = s2; sui = u; } }); await wait(60);
    t('an undefined setting starts unchecked', !input('define').checked);
    fill('define', true); fill('value', '3'); sh.ok(); await wait(80);
    t('Suggested Value Changes for the lockout duration and reset counter', title() === 'Suggested Value Changes' && dlgText().includes('Because the value of Account lockout threshold is now 3 invalid logon attempts') && dlgText().includes('Reset account lockout counter after'));
    if (stop('suggest')) return;
    await click('OK'); await busy;
    t('threshold 3 plus the suggested 10 minutes', lt.computer.LockoutBadCount === 3 && lt.computer.LockoutDuration === 10 && lt.computer.ResetLockoutCount === 10);
    busy = WS.gpme.securityDialog(lt, 'computer', 'SeRemoteInteractiveLogonRight', { onCreate: (s2, u) => { sh = s2; sui = u; } }); await wait(60);
    fill('define', true); await sui.add([{ principal: 'BUILTIN\\Administrators' }, { principal: 'CONTOSO\\Sales Staff' }]); sh.ok(); await busy;
    t('User Rights Assignment: Add User or Group...', lt.computer.SeRemoteInteractiveLogonRight.join() === 'BUILTIN\\Administrators,CONTOSO\\Sales Staff');
    busy = WS.gpme.securityDialog(lt, 'computer', 'svc:Spooler', { onCreate: (s2, u) => { sh = s2; sui = u; } }); await wait(60);
    t('System Services: Print Spooler Properties', title() === 'Print Spooler Properties' && dlgText().includes('Select service startup mode:'));
    fill('define', true); fill('disabled', true); sh.ok(); await busy;
    t('...Disabled', lt.computer['svc:Spooler'] === 'Disabled' && /"Spooler",4/.test(WS.fs.readFile(G.gpoDir(lt) + '\\Machine\\Microsoft\\Windows NT\\SecEdit\\GptTmpl.inf')));
    ec.open('gpme:u.adm.cp'); await wait(60);
    const rowsNow = emmc.list.rows();
    t('Administrative Templates > Control Panel: sub-folders first, then settings', rowsNow.slice(0, 3).every(r => r.kind === 'folder') && rowsNow.some(r => r.kind === 'setting' && r.def.key === 'NoControlPanel'));
    emmc.list.select(['setting:NoControlPanel']); await wait(40);
    t('the Extended view describes the selected setting', edw.el.querySelector('.mmc-ext').textContent.includes('Requirements:') && edw.el.querySelector('.mmc-ext').textContent.includes('At least Windows 2000'));
    let pd = null;
    busy = WS.gpme.policyDialog(ddp, 'user', 'NoControlPanel', { onCreate: a => { pd = a; }, list: WS.gpoCatalog.inNode('u.adm.cp') }); await wait(60);
    t('policy dialog: Not Configured, Comment, Supported on, Options, Help', title() === 'Prohibit access to Control Panel and PC settings' && input('notConfigured').checked && dlgText().includes('Supported on:') && dlgText().includes('Help:'));
    if (stop('policy')) return;
    pd.set('Enabled'); pd.comment('No Control Panel for admins either'); pd.next(); await wait(60);
    t('Next Setting applies and moves on', ddp.user.NoControlPanel && ddp.user.NoControlPanel.state === 'Enabled' && ddp.user.NoControlPanel.comment === 'No Control Panel for admins either' && pd.def.key !== 'NoControlPanel');
    await click('Cancel'); await busy;
    G.setSetting(ddp, 'user', 'NoControlPanel', null);
    busy = WS.gpme.policyDialog(ddp, 'user', 'DisableCMD', { onCreate: a => { pd = a; } }); await wait(60);
    pd.set('Enabled'); pd.option('DisableCMD', '1'); pd.ok(); await busy;
    t('options: Disable the command prompt script processing also? Yes', ddp.user.DisableCMD.options.DisableCMD === 1);
    G.setSetting(ddp, 'user', 'DisableCMD', null);
    ec.open('gpme:u.adm.all'); await wait(60);
    t('All Settings lists every user policy with its path', emmc.list.rows().length === WS.gpoCatalog.policiesUnder('u.adm').length && edw.el.textContent.includes('\\Control Panel'));
    busy = WS.gpme.properties(ddp, { onCreate: (s2, u) => { sh = s2; sui = u; } }); await wait(60);
    sh.show(3); await wait(30); fill('comment', 'Domain-wide password and lockout policy'); sh.ok(); await busy;
    t('root Properties > Comment', ddp.description === 'Domain-wide password and lockout policy');
    const lw = WS.apps.launch('gpedit'), lc2 = lw.gpme; await wait(100);
    lc2.open('gpme:c.sec.pw'); await wait(60);
    const ltree = lw.el.querySelector('.mmc-tree').textContent;
    t('gpedit.msc: Local Computer Policy without Policies/Preferences or Kerberos Policy', ltree.includes('Local Computer Policy') && !ltree.includes('Preferences') && !ltree.includes('Kerberos Policy') && lw.el.textContent.includes('Security Setting'));
    if (stop('gpedit')) return;
    lw.close(); edw.close();
    const sw2 = WS.gpme.open({ starter: G.starter('Kiosk Lockdown').id }); await wait(80);
    t('the Starter GPO editor shows only Administrative Templates', !sw2.el.querySelector('.mmc-tree').textContent.includes('Windows Settings') && sw2.el.querySelector('.mmc-tree').textContent.includes('Administrative Templates'));
    sw2.close();

    /* ================================================================ effects on this server */
    const adminLock = G.create('Admin Lockdown').gpo; G.link(adminLock, 'contoso.local');
    G.setSetting(adminLock, 'user', 'NoControlPanel', 'Enabled');
    G.setSetting(adminLock, 'user', 'DisableCMD', { state: 'Enabled', options: { DisableCMD: 2 } });
    G.setSetting(adminLock, 'user', 'NoRecycleBinIcon', 'Enabled');
    G.setSetting(adminLock, 'user', 'NoClose', 'Enabled');
    G.setSetting(adminLock, 'user', 'EnableScripts', { state: 'Enabled', options: { ExecutionPolicy: 'AllSigned' } });
    G.setSetting(adminLock, 'user', 'NoDrives', { state: 'Enabled', options: { NoDrives: 4 } });
    G.setSetting(adminLock, 'user', 'NoRecycleFiles', 'Enabled');
    const dcp = G.get(G.DDCP);
    G.setSetting(dcp, 'computer', 'LegalNoticeCaption', 'Authorized use only');
    G.setSetting(dcp, 'computer', 'LegalNoticeText', 'Activity on this server is monitored.');
    G.setSetting(dcp, 'computer', 'svc:Spooler', 'Disabled');
    const sysdm = WS.apps.launch('sysdm'); await wait(60);
    t('before policy is processed nothing changes: System Properties opens', !!sysdm && title() === 'System Properties');
    await click('Cancel'); await wait(30);
    let out2 = await crun('gpupdate');
    t('gpupdate: computer and user policy updated', out2.includes('Updating policy...') && out2.includes('Computer Policy update has completed successfully.') && out2.includes('User Policy update has completed successfully.'));
    t('Control Panel items are blocked with the Restrictions message', WS.apps.launch('sysdm') === null && title() === 'Restrictions' && dlgText().includes('This operation has been cancelled due to restrictions in effect on this computer.'));
    await click('OK');
    t('the Recycle Bin icon is gone from the desktop', !document.getElementById('desktop-icons').textContent.includes('Recycle Bin'));
    t('the power menu has no Shut down or Restart', WS.shell.powerItems().every(([l]) => !/Shut down|Restart/.test(l)));
    t('System Services in the DC policy set the Print Spooler to Disabled', WS.svc.get('Spooler').startup === 'Disabled');
    const exw = WS.apps.launch('explorer'); await wait(80);
    const pcText = exw.el.querySelector('.ex-main').textContent;
    t('Hide these specified drives: C: is gone from This PC', !pcText.includes('(C:)') && !exw.el.querySelector('.ex-tree').textContent.includes('(C:)'), pcText.slice(0, 200));
    WS.fs.writeFile('C:\\Users\\Administrator\\Desktop\\note.txt', 'temp');
    exw.close();
    const exw2 = WS.apps.launch('explorer', { path: 'C:\\Users\\Administrator\\Desktop' }); await wait(80);
    t('...but typing the path still works, as on Windows', exw2.el.querySelector('.ex-main').textContent.includes('note.txt'));
    const binBefore = WS.fs.recycleBin().length;
    const del = exw2.explorer.remove(['note.txt']); await wait(60);
    t('Do not move deleted files to the Recycle Bin: Delete asks to delete permanently', dlgText().includes('Are you sure you want to permanently delete this file?'));
    await click('Yes'); await del;
    t('...and the file does not go to the Recycle Bin', !WS.fs.exists('C:\\Users\\Administrator\\Desktop\\note.txt') && WS.fs.recycleBin().length === binBefore);
    exw2.close();
    const dc = new WS.term.TextConsole(), dcs = new WS.term.CmdSession({ console: dc });
    dcs.banner(); await dcs.repl();
    t('Command Prompt: "The command prompt has been disabled by your administrator."', dc.text().includes('The command prompt has been disabled by your administrator.') && dc.text().includes('Press any key to continue . . .') && dcs.exited && !dc.text().includes('Microsoft Windows [Version'));
    t('cmd /c still runs (scripts allowed)', (await crun('cmd /c echo still works')).includes('still works'));
    const epl = await run('Get-ExecutionPolicy -List');
    t('Get-ExecutionPolicy -List: UserPolicy AllSigned from Group Policy', epl.find(x => x.Scope === 'UserPolicy').ExecutionPolicy === 'AllSigned' && (await run('Get-ExecutionPolicy'))[0] === 'AllSigned');
    out2 = await runText('Set-ExecutionPolicy Unrestricted -Force');
    t('Set-ExecutionPolicy reports the Group Policy override', out2.includes('overridden by a policy defined at a more specific scope'));
    out2 = await crun('gpresult /r');
    t('gpresult /r: header and computer settings', out2.includes(`RSOP data for CONTOSO\\Administrator on ${WS.sys.name} : Logging Mode`) && out2.includes('COMPUTER SETTINGS') && out2.includes(`CN=${WS.sys.name},OU=Domain Controllers,DC=contoso,DC=local`), out2.slice(0, 600));
    t('gpresult /r: applied and filtered GPOs for the user', out2.includes('USER SETTINGS') && out2.includes('Admin Lockdown') && out2.includes('Filtering:  Not Applied (Empty)'));
    out2 = await crun('gpresult /r /scope computer');
    t('/scope computer leaves out the user', !out2.includes('USER SETTINGS') && out2.includes('The computer is a part of the following security groups'));
    out2 = await crun('gpresult /v /scope computer');
    t('gpresult /v lists the resultant settings', out2.includes('Resultant Set Of Policies for Computer') && out2.includes('MinimumPasswordLength') && out2.includes('Startup Mode:      Disabled'));
    await crun('gpresult /h C:\\Reports\\rsop.html');
    t('gpresult /h writes the HTML report', WS.fs.readFile('C:\\Reports\\rsop.html').includes('Applied GPOs'));
    t('...and refuses to overwrite without /f', (await crun('gpresult /h C:\\Reports\\rsop.html')).includes('already exists') && !(await crun('gpresult /h C:\\Reports\\rsop.html /f')).includes('already exists'));
    t('gpresult without a switch shows the usage', (await crun('gpresult')).includes('GPRESULT [/S system'));
    WS.shell.legalNotice(); await wait(80);
    t('the logon banner appears before the sign-in screen', document.querySelector('.overlay.legal') && document.querySelector('.overlay.legal').textContent.includes('Authorized use only') && document.querySelector('.overlay.legal').textContent.includes('Activity on this server is monitored.'));
    if (stop('banner')) return;
    [...document.querySelectorAll('.overlay.legal button')].find(b => b.textContent === 'OK').click(); await wait(60);
    t('OK goes on to the sign-in screen', !!document.querySelector('.overlay.login:not(.legal)'));
    WS.shell.startSession('Administrator'); await wait(100);
    G.remove(adminLock); await crun('gpupdate'); await wait(60);
    t('removing the GPO and updating lifts the user restrictions', !!WS.shell.powerItems().length && !WS.shell.restricted('sysdm') && document.getElementById('desktop-icons').textContent.includes('Recycle Bin'));

    /* ================================================================ GroupPolicy PowerShell module */
    let o = await run('Get-GPO -Name "Default Domain Policy"');
    t('Get-GPO: DisplayName, Id without braces, GpoStatus', o[0].DisplayName === 'Default Domain Policy' && o[0].Id === '31b2f340-016d-11d2-945f-00c04fb984f9' && o[0].GpoStatus === 'AllSettingsEnabled' && /AD Version: \d+, SysVol Version: \d+/.test(o[0].ComputerVersion));
    out2 = await runText('Get-GPO -Name Nope');
    t('Get-GPO: not found error', out2.includes("A GPO with the display name 'Nope' could not be found in the contoso.local domain.") && out2.includes('GpoWithNameNotFound'));
    o = await run('New-GPO -Name "PS Test" -Comment "made in PowerShell" | New-GPLink -Target "OU=Sales,DC=contoso,DC=local" -Enforced Yes');
    t('New-GPO | New-GPLink', o[0].DisplayName === 'PS Test' && o[0].Enforced === true && o[0].Target === 'OU=Sales,DC=contoso,DC=local' && G.get('PS Test').description === 'made in PowerShell');
    o = await run('Get-GPInheritance -Target "OU=Sales,DC=contoso,DC=local"');
    t('Get-GPInheritance: links and inherited links', o[0].ContainerType === 'OU' && o[0].GpoInheritanceBlocked === 'No' && o[0].GpoLinks.includes('PS Test') && o[0].InheritedGpoLinks.includes('Default Domain Policy'));
    o = await run('Set-GPInheritance -Target "OU=Sales,DC=contoso,DC=local" -IsBlocked Yes');
    t('Set-GPInheritance -IsBlocked Yes', o[0].GpoInheritanceBlocked === 'Yes' && G.isBlocked('Sales'));
    G.setBlockInheritance('Sales', false);
    o = await run('Set-GPLink -Name "PS Test" -Target "OU=Sales,DC=contoso,DC=local" -LinkEnabled No -Order 1');
    t('Set-GPLink: disabled, order 1', o[0].Enabled === false && o[0].Order === 1);
    o = await run('Get-GPPermission -Name "PS Test" -All');
    t('Get-GPPermission -All', o.some(p => p.Permission === 'GpoApply' && String(p.Trustee.Name) === 'Authenticated Users') && o.some(p => p.Permission === 'GpoEditDeleteModifySecurity'));
    await run('Set-GPPermission -Name "PS Test" -TargetName "Sales Staff" -TargetType Group -PermissionLevel GpoApply');
    t('Set-GPPermission', G.filtering('PS Test').some(p => p.short === 'Sales Staff'));
    await run('Set-GPRegistryValue -Name "PS Test" -Key "HKLM\\Software\\Policies\\Microsoft\\Windows\\Server\\ServerManager" -ValueName DoNotOpenAtLogon -Type DWord -Value 1');
    o = await run('Get-GPRegistryValue -Name "PS Test" -Key "HKLM\\Software\\Policies\\Microsoft\\Windows\\Server\\ServerManager"');
    t('Set/Get-GPRegistryValue map to Do not display Server Manager automatically at logon', o[0].ValueName === 'DoNotOpenAtLogon' && o[0].Value === 1 && G.get('PS Test').computer.DoNotOpenAtLogon.state === 'Enabled');
    o = await run('Get-GPOReport -Name "PS Test" -ReportType Xml');
    t('Get-GPOReport -ReportType Xml', typeof o[0] === 'string' && o[0].includes('<Name>PS Test</Name>') && o[0].includes('Do not display Server Manager automatically at logon'));
    await run('Get-GPOReport -All -ReportType Html -Path C:\\Reports\\all.html');
    t('Get-GPOReport -All -Path', WS.fs.readFile('C:\\Reports\\all.html').includes('Default Domain Controllers Policy'));
    o = await run('Backup-GPO -Name "PS Test" -Path C:\\GPOBackup -Comment "before removal"');
    t('Backup-GPO', o[0].DisplayName === 'PS Test' && o[0].BackupDirectory === 'C:\\GPOBackup' && o[0].Comment === 'before removal');
    await run('Remove-GPO -Name "PS Test" -Confirm:$false');
    t('Remove-GPO', !G.get('PS Test'));
    o = await run('Restore-GPO -Name "PS Test" -Path C:\\GPOBackup');
    t('Restore-GPO', o[0].DisplayName === 'PS Test' && !!G.get('PS Test'));
    o = await run('Copy-GPO -SourceName "PS Test" -TargetName "PS Copy"');
    t('Copy-GPO', o[0].DisplayName === 'PS Copy' && G.get('PS Copy').computer.DoNotOpenAtLogon.state === 'Enabled');
    o = await run('Rename-GPO -Name "PS Copy" -TargetName "PS Renamed"');
    t('Rename-GPO', o[0].DisplayName === 'PS Renamed');
    o = await run('Get-GPO -All');
    t('Get-GPO -All lists every GPO, sorted', o.length === G.list().length && o[0].DisplayName <= o[1].DisplayName);
    await run('Invoke-GPUpdate -Force');
    t('Invoke-GPUpdate processes policy', WS.state.events.logs.System.slice(-1)[0].id === 1503 || WS.state.events.logs.System.slice(-2).some(e => e.id === 1502));
    await run('Get-GPResultantSetOfPolicy -ReportType Html -Path C:\\Reports\\rsop2.html');
    t('Get-GPResultantSetOfPolicy', WS.fs.readFile('C:\\Reports\\rsop2.html').includes('Group Policy Results'));
    o = await run('Get-GPStarterGPO -All');
    t('Get-GPStarterGPO -All', o.some(x => x.StarterGpoType === 'System') && o.some(x => x.DisplayName === 'Kiosk Lockdown'));
    cmdc.feed('Y');
    out2 = await crun('dcgpofix /target:domain');
    t('dcgpofix restores the Default Domain Policy', out2.includes('The Default Domain Policy was restored successfully') && G.get(G.DDP).computer.MinimumPasswordLength === 7);

    console.log(`RESULT ${pass} passed, ${fail} failed`);
  } catch (e) {
    console.log('FAIL exception :: ' + (e && e.stack || e));
    console.log(`RESULT ${pass} passed, ${fail + 1} failed`);
  }
})();
